---
title: 'Individual Data Sets: AQEM Romania'
author: "Jonathan Jupke"
output: html_document
---

```{r SETUP, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning=FALSE,
                      message = FALSE)
pacman::p_load(
        ade4,
        cluster,
        corrplot,
        data.table,
        dplyr,
        ggplot2,
        indicspecies,
        magrittr,
        mapview,
        sf,
        tidyr,
        tmap,
        vegan
)
source("../helper_functions.R")
tmap_mode("view")
```

```{r CREATE OPTIONS}
#- What to load and what to compute
#- TRUE means load
options <- list(
  mantel = TRUE,
  pre =      TRUE,
  distance = TRUE,
  anosim =   TRUE,
  typical =  TRUE,
  iv      =  TRUE, 
  cs      =  FALSE
)
```


```{r CREATE GLOBAL VARIABLES 1}
data.set = "AQEM_romania"
all_seasons <- c("spring", "summer", "autumn", "winter")
seasons <- 1:3
```


```{r CREATE DA, LI and PU}
most.recent.data <-
  fs::dir_ls("../../data/02_combined_data/", regexp = "_core_taxa_data_aggregated.rds") |>
  stringr::str_remove("../../data/02_combined_data/02_") |>
  stringr::str_remove("_core_taxa_data_aggregated.rds") |>
  lubridate::ymd() |>
  {
    \(x) x[which.max(x)]
  }()

data <-
  readRDS(
    file = paste0(
      "../../data/02_combined_data/02_",
      most.recent.data,
      "_core_taxa_data_aggregated.rds"
    )
  )
lapply(data, function(x) unique(x$data.set))

da <-
        lapply(data, function(x)
                x[data.set == "Project AQEM (Romania)"])

# #- create subset of least impacted sites
# li <-
#         lapply(seasons, function(x)
#                 da[[x]][fec.least.impacted == TRUE])
# #- create subset of sites that are least impacted and removed from regional borders
# pu <-
#         lapply(seasons, function(x)
#                 li[[x]][illies_distance >= 25000 & bgr_distance >= 25000])
```

```{r PLOT MAPS }
map <- 
  rbindlist(da) |> 
  unique(by = "gr_sample_id") |> 
  st_as_sf()
tm_shape(map) + tm_dots(col = "brt12") + tm_facets(by = "season")
```


```{r CHECK TYPOLOGIES, results = 'hide'}
#- check how many instances of each type are there
map |> filter(season == "spring") |> pull(bgr) |> table()
map |> filter(season == "summer") |> pull(bgr) |> table()
map |> filter(season == "autumn") |> pull(bgr) |> table()
map |> filter(season == "spring") |> pull(illies) |> table()
map |> filter(season == "summer") |> pull(illies) |> table()
map |> filter(season == "autumn") |> pull(illies) |> table()
map |> filter(season == "spring") |> pull(brt12) |> table()
map |> filter(season == "summer") |> pull(brt12) |> table()
map |> filter(season == "autumn") |> pull(brt12) |> table()

nrow(da[[1]][is.na(species)])/nrow(da[[1]])
```

```{r GLOBAL VARIBLES 2}

typologies <- c("brt12", "illies", "brt12_illies","brt12_bgr", "bgr")
```


```{r RUN PRE2 AND 3}
if (!options$pre){ 

        das2 <- prep1(data = da, 
                      taxon = "species")
        dag2 <- prep1(data = da,
                      taxon = "genus")
        daf2 <- prep1(data = da,
                      taxon = "family")
        lis2 <- prep1(data = li,
                      taxon = "species")
        lig2 <- prep1(data = li,
                      taxon = "genus")
        lif2 <- prep1(data = li,
                      taxon = "family")
        pus2 <- prep1(data = pu,
                      taxon = "species")
        pug2 <- prep1(data = pu,
                      taxon = "genus")
        puf2 <- prep1(data = pu,
                      taxon = "family")
        lis2.abu <- prep1(data = li, taxon = "species", abundance.to.pa = FALSE)
        lig2.abu <- prep1(data = li, taxon = "genus", abundance.to.pa = FALSE)
        lif2.abu <- prep1(data = li, taxon = "family", abundance.to.pa = FALSE)
        
  das3 <- prep2(das2)
  lis3 <- prep2(lis2)
  pus3 <- prep2(pus2)
  dag3 <- prep2(dag2)
  lig3 <- prep2(lig2)
  pug3 <- prep2(pug2)
  daf3 <- prep2(daf2)
  lif3 <- prep2(lif2)
  puf3 <- prep2(puf2)
  lis3.abu <- prep2(lis2.abu) 
  lig3.abu <- prep2(lig2.abu) 
  lif3.abu <- prep2(lif2.abu) 
  
  saveRDS(
          object = list(
                  das2 = das2,
                  lis2 = lis2,
                  pus2 = pus2,
                  dag2 = dag2,
                  lig2 = lig2,
                  pug2 = pug2,
                  dag3 = dag3,
                  lig3 = lig3,
                  pug3 = pug3,
                  daf2 = daf2,
                  lif2 = lif2,
                  puf2 = puf2,
                  daf3 = daf3,
                  lif3 = lif3,
                  puf3 = puf3,
                  lis3.abu = lis3.abu,
                  lig3.abu = lig3.abu,
                  lif3.abu = lif3.abu
          ),
          
    file = paste0("auxilliary/pre_",data.set,".rds")
  )
} else if (options$pre){
  pre = readRDS(file = paste0("auxilliary/pre_",data.set,".rds"))
  for (i in seq_along(pre)){
    assign(x     = names(pre)[i], 
           value = pre[[i]])
  }
}
```

```{r COMPUTE DISTANCE MATRICES}
# DISTANCE MATRIX  ------------------------------------------------------------------
if (!options$distance) {
  das.dist <- das3 |> prep3()
  lis.dist <- lis3 |> prep3()
  pus.dist <- pus3 |> prep3()
  dag.dist <- dag3 |> prep3()
  lig.dist <- lig3 |> prep3()
  pug.dist <- pug3 |> prep3()
  daf.dist <- daf3 |> prep3()
  lif.dist <- lif3 |> prep3()
  puf.dist <- puf3 |> prep3()
  lis.abu.dist  <- lis3.abu |> prep3()
  lig.abu.dist  <- lig3.abu |> prep3()
  lif.abu.dist  <- lif3.abu |> prep3()

  saveRDS(
          object = list(
                  das.dist = das.dist,
                  lis.dist = lis.dist,
                  pus.dist = pus.dist,
                  dag.dist = dag.dist,
                  lig.dist = lig.dist,
                  pug.dist = pug.dist,
                  daf.dist = daf.dist,
                  lif.dist = lif.dist,
                  puf.dist = puf.dist,
                  lis.abu.dist = lis.abu.dist,
                  lig.abu.dist = lig.abu.dist,
                  lif.abu.dist = lif.abu.dist
          ),
          file = paste0("auxilliary/distance_", data.set, ".rds")
  )
} else if (options$distance) {
  distance_list = readRDS(file = paste0("auxilliary/distance_", data.set, ".rds"))
  for (i in seq_along(distance_list)) {
    assign(x     = names(distance_list)[i],
           value = distance_list[[i]])
  }
}
```

\newpage
# Mantel test 
```{r COMPUTE MANTEL TEST}
if (!options$mantel){
  
  
  #- species (abu) to species (pa)
  m1 <- lapply(1:2, function(x) mantel.rtest(lis.dist[[x]], lis.abu.dist[[x]]))
  #- species (abu) to genus (abu)
  m2 <- lapply(1:2, function(x) mantel.rtest(lis.abu.dist[[x]], lig.abu.dist[[x]]))
  #- species (abu) to genus (pa)
  m3 <- lapply(1:2, function(x) mantel.rtest(lis.abu.dist[[x]], lig.dist[[x]]))
  #- species (abu) to family (abu)
  m4 <- lapply(1:2, function(x) mantel.rtest(lis.abu.dist[[x]], lif.abu.dist[[x]]))
  #- species (abu) to family (pa)
  m5 <- lapply(1:2, function(x) mantel.rtest(lis.abu.dist[[x]], lif.dist[[x]]))
  #- species (pa) to genus (abu)
  m6 <- lapply(1:2, function(x) mantel.rtest(lis.dist[[x]], lig.abu.dist[[x]]))
   #- species (PA) to genus (PA)
  m7 <- lapply(1:2, function(x) mantel.rtest(lis.dist[[x]], lig.dist[[x]]))
  #- species (pa) to family (abu)
  m8 <- lapply(1:2, function(x) mantel.rtest(lis.dist[[x]], lif.abu.dist[[x]]))
  #- species (PA) to family (PA)
  m9 <- lapply(1:2, function(x) mantel.rtest(lis.dist[[x]], lif.dist[[x]]))
  #- genus (ABU) to genus (PA)
  m10 <- lapply(1:2, function(x) mantel.rtest(lig.abu.dist[[x]], lig.dist[[x]]))
  #- genus to family (ABU)
  m11 <- lapply(1:2, function(x) mantel.rtest(lig.abu.dist[[x]], lif.abu.dist[[x]]))
  #- genus (abu) to family (pa)
  m12 <- lapply(1:2, function(x) mantel.rtest(lig.abu.dist[[x]], lif.dist[[x]]))
  #- genus (pa) to family (abu)
  m13 <- lapply(1:2, function(x) mantel.rtest(lig.dist[[x]], lif.abu.dist[[x]]))
  #- genus (PA) to family (PA)
  m14 <- lapply(1:2, function(x) mantel.rtest(lig.dist[[x]], lif.dist[[x]]))
  #- family (ABU) to family (PA)
  m15 <- lapply(1:2, function(x) mantel.rtest(lif.abu.dist[[x]], lif.dist[[x]]))

  saveRDS(list(
    m1 = m1, 
    m2 = m2,
    m3 = m3,
    m4 = m4,
    m5 = m5,
    m6  = m6,
    m7  = m7,
    m8  = m8,
    m9  = m9,
    m10 = m10,
    m11 = m11,
    m12 = m12,
    m13 = m13,
    m14 = m14,
    m15 = m15
    ), 
    file = paste0("auxilliary/mantel_", data.set, ".rds"))
  
} else {
  mantel.list = readRDS(file = paste0("auxilliary/mantel_", data.set, ".rds"))
  for (i in seq_along(mantel.list)) {
    assign(x     = names(mantel.list)[i],
           value = mantel.list[[i]])
  }
}  

#- correlation marices for each season 
mantel.spring <- matrix(0,nrow = 6, ncol = 6)
mantel.summer <- matrix(0,nrow = 6, ncol = 6)
mantel.autumn <- matrix(0,nrow = 6, ncol = 6)
diag(mantel.spring) <- 1
diag(mantel.summer) <- 1
diag(mantel.autumn) <- 1
tax.lvl <- c("species (abu)", "species (pa)","genus (abu)","genus (pa)", "family (abu)", "family (pa)")
rownames(mantel.spring) = colnames(mantel.spring) = tax.lvl
rownames(mantel.summer) = colnames(mantel.summer) = tax.lvl
rownames(mantel.autumn) = colnames(mantel.autumn) = tax.lvl
from.vec <- rep(tax.lvl, times = c(5,4,3,2,1,0))

mantel.results <- data.table(
  from = rep(from.vec, each = 2),
  to   = rep(c(
    "species (pa)" ,"genus (abu)","genus (pa)" ,"family (abu)", "family (pa)",
                    "genus (abu)","genus (pa)" ,"family (abu)", "family (pa)",
                                  "genus (pa)" ,"family (abu)", "family (pa)",
                                                "family (abu)", "family (pa)",
                                                                "family (pa)"),
    each = 2),
  statistic = c(
    lapply(m1, function(x) round(x$obs,3)), 
    lapply(m2, function(x) round(x$obs,3)), 
    lapply(m3, function(x) round(x$obs,3)), 
    lapply(m4, function(x) round(x$obs,3)),
    lapply(m5, function(x) round(x$obs,3)),
    lapply(m6, function(x) round(x$obs,3)),
    lapply(m7, function(x) round(x$obs,3)), 
    lapply(m8, function(x) round(x$obs,3)), 
    lapply(m9, function(x) round(x$obs,3)), 
    lapply(m10, function(x) round(x$obs,3)),
    lapply(m11, function(x) round(x$obs,3)),
    lapply(m12, function(x) round(x$obs,3)),
    lapply(m13, function(x) round(x$obs,3)),
    lapply(m14, function(x) round(x$obs,3)),
    lapply(m15, function(x) round(x$obs,3))
    ),
  p.value   = c(
    lapply(m1, function(x) round(x$pvalue,3)), 
    lapply(m2, function(x) round(x$pvalue,3)), 
    lapply(m3, function(x) round(x$pvalue,3)), 
    lapply(m4, function(x) round(x$pvalue,3)),
    lapply(m5, function(x) round(x$pvalue,3)),
    lapply(m6, function(x) round(x$pvalue,3)),
    lapply(m7, function(x) round(x$pvalue,3)),
    lapply(m8, function(x) round(x$pvalue,3)),
    lapply(m9, function(x) round(x$pvalue,3)),
    lapply(m10, function(x) round(x$pvalue,3)),
    lapply(m11, function(x) round(x$pvalue,3)),
    lapply(m12, function(x) round(x$pvalue,3)),
    lapply(m13, function(x) round(x$pvalue,3)),
    lapply(m14, function(x) round(x$pvalue,3)),
    lapply(m15, function(x) round(x$pvalue,3))
    ),
  season = c("spring", "summer")
)
#- loop over seasons 
for (i in 1:2){
 i.season <- c("spring", "summer", "autumn")[i]
 i.x      <- get(paste0("mantel.",i.season))
 for (k in 1:nrow(i.x)){ for (j in 1:ncol(i.x)){
     if (k == j) next()
     j.from = rownames(i.x)[k]; j.to   = colnames(i.x)[j]
     j.sub  = mantel.results[from == j.from & to == j.to & season == i.season, statistic]
     j.sub %<>% unlist()
     if (is.null(j.sub)) {
       j.sub  = mantel.results[from == j.to & to == j.from & season == i.season, statistic]
       j.sub %<>% unlist()
       if (is.null(j.sub)) next()
     }
     i.x[k,j] <- j.sub
     rm(list = ls()[grepl("^j\\.",ls())])
 }}
 assign(paste0("mantel.",i.season), i.x)
 rm(list = ls()[grepl("^i\\.",ls())])
}

corrplot(mantel.spring, method = "shade", type = "lower", diag = FALSE, addCoef.col = "black", mar=c(0,0,1,0), 
         title = "spring", tl.srt=0, tl.col = "black", tl.offset = 1, col = viridisLite::rocket(n = 100))
corrplot(mantel.summer, method = "shade", type = "lower", diag = FALSE, addCoef.col = "black", mar=c(0,0,1,0), 
         title = "summer", tl.srt=0, tl.col = "black", tl.offset = 1, col = viridisLite::rocket(n = 100))

```

\newpage
# Point biserial Correlation through indicspecies 

```{r COMPUTE PBC}
if (!options$iv){
        ivsas <- ivs(data2 = das2, data3 = das3, season.data = 1:3, typologies = typologies, add = "all observations")
        ivsls <- ivs(data2 = lis2, data3 = lis3, season.data = 1:3, typologies = typologies, add = "least impacted")
        ivsps <- ivs(data2 = pus2, data3 = pus3, season.data = 1:3, typologies = typologies, add = "purified")
        ivsag <- ivs(data2 = dag2, data3 = dag3, season.data = 1:3, typologies = typologies, add = "all observations")
        ivslg <- ivs(data2 = lig2, data3 = lig3, season.data = 1:3, typologies = typologies, add = "least impacted")
        ivspg <- ivs(data2 = pug2, data3 = pug3, season.data = 1:3, typologies = typologies, add = "purified")
        ivsaf <- ivs(data2 = daf2, data3 = daf3, season.data = 1:3, typologies = typologies, add = "all observations")
        ivslf <- ivs(data2 = lif2, data3 = lif3, season.data = 1:3, typologies = typologies, add = "least impacted")
        ivspf <- ivs(data2 = puf2, data3 = puf3, season.data = 1:3, typologies = typologies, add = "purified")
         saveRDS(
          object = list(
                  ivsas = ivsas,
                  ivsls = ivsls,
                  ivsps = ivsps,
                  ivsag = ivsag,
                  ivslg = ivslg,
                  ivspg = ivspg,
                  ivsaf = ivsaf,
                  ivslf = ivslf,
                  ivspf = ivspf
          ),
          file = paste0("auxilliary/iv_", data.set, ".rds")
  )
} else {
        iv.list <- readRDS(file = paste0("auxilliary/iv_", data.set, ".rds"))
        for (i in seq_along(iv.list)) assign(x = names(iv.list)[i], value = iv.list[[i]])
        rm(iv.list)
}
iv_spe <- rbindlist(list(ivsas, ivsls, ivsps))
iv_gen <- rbindlist(list(ivsag, ivslg, ivspg))
iv_fam <- rbindlist(list(ivsaf, ivslf, ivspf))

iv_spe_mean  <- iv_spe[,mean(indval), by = c("typology", "type")]
iv_spe_mean[,c("taxon.level", "variable") := .("species" , "ivs_corr")]
iv_gen_mean  <- iv_gen[,mean(indval), by = c("typology", "type")]
iv_gen_mean[,c("taxon.level", "variable") := .("genus" , "ivs_corr")]
iv_fam_mean  <- iv_fam[,mean(indval), by = c("typology", "type")]
iv_fam_mean[,c("taxon.level", "variable") := .("family" , "ivs_corr")]
```

```{r PLOT PBC}
ivs.plot1(iv_spe, taxon = "species")
ivs.plot1(iv_gen, taxon = "genus")
ivs.plot1(iv_fam, taxon = "family")
```

```{r COMPUTE CLASSIFICATION STRENGTH}
if (!options$cs) {
     csas <- class.strength(data2 = das2, data4 = das.dist, season.data = 1:3, add = "all observations")
     csls <- class.strength(data2 = lis2, data4 = lis.dist, season.data = 1:3, add = "least impacted")
     csps <- class.strength(data2 = pus2, data4 = pus.dist, season.data = 1:3, add = "purified")
     csag <- class.strength(data2 = dag2, data4 = dag.dist, season.data = 1:3, add = "all observations")
     cslg <- class.strength(data2 = lig2, data4 = lig.dist, season.data = 1:3, add = "least impacted")
     cspg <- class.strength(data2 = pug2, data4 = pug.dist, season.data = 1:3, add = "purified")
     csaf <- class.strength(data2 = daf2, data4 = daf.dist, season.data = 1:3, add = "all observations")
     cslf <- class.strength(data2 = lif2, data4 = lif.dist, season.data = 1:3, add = "least impacted")
     cspf <- class.strength(data2 = puf2, data4 = puf.dist, season.data = 1:3, add = "purified")   
     saveRDS(
             object = list(
                     csas = csas,
                     csls = csls,
                     csps = csps,
                     csag = csag,
                     cslg = cslg,
                     cspg = cspg,
                     csaf = csaf,
                     cslf = cslf,
                     cspf = cspf
             ),
             file = paste0("auxilliary/cs_", data.set, ".rds")
     )
} else {
        cs.list <- readRDS(file = paste0("auxilliary/iv_", data.set, ".rds"))
        for (i in seq_along(cs.list)) assign(x = names(cs.list)[i], value = cs.list[[i]])
        rm(cs.list)
}
cs_spe <- rbindlist(list(csas, csls, csps))
cs_gen <- rbindlist(list(csag, cslg, cspg))
cs_fam <- rbindlist(list(csaf, cslf, cspf))

cs_spe_mean  <- cs_spe[,mean(cs), by = c("typology", "type")]
cs_gen_mean  <- cs_gen[,mean(cs), by = c("typology", "type")]
cs_fam_mean  <- cs_fam[,mean(cs), by = c("typology", "type")]
cs_spe_mean[,c("taxon.level", "variable") := .("species", "cs")]
cs_gen_mean[,c("taxon.level", "variable") := .("genus"  , "cs")]
cs_fam_mean[,c("taxon.level", "variable") := .("family" , "cs")]

```

```{r PLOT CLASSIFICATION STRENGTH}
class.strength.plot1(cs_spe, taxon = "species")
class.strength.plot2(cs_spe, taxon = "species")
class.strength.plot3(cs_spe, taxon = "species")
class.strength.plot1(cs_gen, taxon = "genus")
class.strength.plot2(cs_gen, taxon = "genus")
class.strength.plot3(cs_gen, taxon = "genus")
class.strength.plot1(cs_fam, taxon = "family")
class.strength.plot2(cs_fam, taxon = "family")
class.strength.plot3(cs_fam, taxon = "family")
```

# Silhouette Width 

```{r COMPUTE SILHOUETTES}
sias      <- wraper_silhouette(data2 = das2, distance = das.dist, add = "all observations")
sils      <- wraper_silhouette(data2 = lis2, distance = lis.dist, add = "least impacted")
sips      <- wraper_silhouette(data2 = pus2, distance = pus.dist, add = "purified")
siag      <- wraper_silhouette(data2 = dag2, distance = dag.dist, add = "all observations")
silg      <- wraper_silhouette(data2 = lig2, distance = lig.dist, add = "least impacted")
sipg      <- wraper_silhouette(data2 = pug2, distance = pug.dist, add = "purified")
siaf      <- wraper_silhouette(data2 = daf2, distance = daf.dist, add = "all observations")
silf      <- wraper_silhouette(data2 = lif2, distance = lif.dist, add = "least impacted")
sipf      <- wraper_silhouette(data2 = puf2, distance = puf.dist, add = "purified")

si_spe <- rbindlist(list(sias, sils, sips))
si_gen <- rbindlist(list(siag, silg, sipg))
si_fam <- rbindlist(list(siaf, silf, sipf))
```


```{r PLOT SILHOUETTES}
silhouette.plot1(x = si_spe, taxon = "species")
silhouette.plot1(x = si_gen, taxon = "genus")
silhouette.plot1(x = si_fam, taxon = "family")
```

# ANOSIM 
```{r COMPUTE ANOSIM}
if (!options$anosim) {
        anas <- wraper_anosim(grouping = das2,distance = das.dist,permutations = 99,add = "all observations")
        anls <- wraper_anosim(grouping = lis2,distance = lis.dist,permutations = 99,add = "least impacted")
        anps <- wraper_anosim(grouping = pus2,distance = pus.dist,permutations = 99,add = "purified")
        anag <- wraper_anosim(grouping = dag2,distance = dag.dist,permutations = 99,add = "all observations")
        anlg <- wraper_anosim(grouping = lig2,distance = lig.dist,permutations = 99,add = "least impacted")
        anpg <- wraper_anosim(grouping = pug2,distance = pug.dist,permutations = 99,add = "purified")
        anaf <- wraper_anosim(grouping = daf2,distance = daf.dist,permutations = 99,add = "all observations")
        anlf <- wraper_anosim(grouping = lif2,distance = lif.dist,permutations = 99,add = "least impacted")
        anpf <- wraper_anosim(grouping = puf2,distance = puf.dist,permutations = 99,add = "purified")
        
        saveRDS(
                object = list(
                        anas = anas,
                        anls = anls,
                        anps = anps,
                        anag = anag,
                        anlg = anlg,
                        anpg = anpg,
                        anaf = anaf,
                        anlf = anlf,
                        anpf = anpf
                ),
                file = paste0("auxilliary/anosim_", data.set, ".rds")
        )
} else if (options$anosim) {
        anosim.list = readRDS(file = paste0("auxilliary/anosim_", data.set, ".rds"))
        for (i in seq_along(anosim.list)) {
                assign(x     = names(anosim.list)[i],
                       value = anosim.list[[i]])
        }
}



an_spe       <- rbindlist(list(anas, anls, anps))
an_spe_mean  <- an_spe[, mean(R), by = c("typology", "type")]
an_spe_mean[, c("taxon.level", "variable") := .("genus" , "Anosim R")]
an_gen  <- rbindlist(list(anag, anlg, anpg))
an_gen_mean  <- an_gen[, mean(R), by = c("typology", "type")]
an_gen_mean[, c("taxon.level", "variable") := .("genus" , "Anosim R")]
an_fam  <- rbindlist(list(anaf, anlf, anpf))
an_fam_mean  <- an_fam[, mean(R), by = c("typology", "type")]
an_fam_mean[, c("taxon.level", "variable") := .("family" , "Anosim R")]
```


```{r PLOT ANOSIM}
anosim.plot1(x = an_spe, taxon = "species")
anosim.plot1(x = an_gen, taxon = "genus")
anosim.plot1(x = an_fam, taxon = "family")
```

# Indicator and Typical taxa
```{r analysis TYPICAL TAXA}
if (!options$typical){
        isas <- indicator_analysis(data2 = das2,data3 = das3,B.lvl = 0.33,add = "all observations")
        isls <- indicator_analysis(data2 = lis2,data3 = lis3,B.lvl = 0.33,add = "least impacted")
        isps <- indicator_analysis(data2 = pus2,data3 = pus3,B.lvl = 0.33,add = "purified")
        isag <- indicator_analysis(data2 = dag2,data3 = dag3,B.lvl = 0.50,add = "all observations")
        islg <- indicator_analysis(data2 = lig2,data3 = lig3,B.lvl = 0.50,add = "least impacted")
        ispg <- indicator_analysis(data2 = pug2,data3 = pug3,B.lvl = 0.50,add = "purified")
        isaf <- indicator_analysis(data2 = daf2,data3 = daf3,B.lvl = 0.66,add = "all observations")
        islf <- indicator_analysis(data2 = lif2,data3 = lif3,B.lvl = 0.66,add = "least impacted")
        ispf <- indicator_analysis(data2 = puf2,data3 = puf3,B.lvl = 0.66,add = "purified")

        saveRDS(
                object = list(
                              isas = isas,
                              isls = isls,
                              isps = isps,
                              isag = isag,
                              islg = islg,
                              ispg = ispg,
                              isaf = isaf,
                              islf = islf,
                              ispf = ispf
                        ),
                file = paste0("auxilliary/indi_typ_", data.set, ".rds")
        )
} else if (options$typical) {
        typical.list <- readRDS(file = paste0("auxilliary/indi_typ_", data.set, ".rds"))
        for (i in seq_along(typical.list)) {
                assign(x     = names(typical.list)[i],
                       value = typical.list[[i]])
        }
}

jac.fam <- rbindlist(list(jaccard_extract(isaf),jaccard_extract(islf),jaccard_extract(ispf)))
mid.fam <- rbindlist(list(mid_extract(isaf),mid_extract(islf),mid_extract(ispf)))
```


```{r PLOT TYPICAL TAXA}
jaccard_plot(jac.fam, "family")
mid_plot(mid.fam, "family")
```

```{r create summary table}
summary.out <- rbindlist(
        list(
        
                an_spe_mean,
                iv_spe_mean,
                cs_spe_mean,
                an_gen_mean,
                iv_gen_mean,
                cs_gen_mean,
                an_fam_mean,
                iv_fam_mean,
                cs_fam_mean
        )
)
fwrite(summary.out, file = paste0(data.set,".csv"))
```