---
title: 'Individual Data Set: BIODROUGHT'
author: "Jonathan Jupke"
output: html_document
---

```{r SETUP, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning=FALSE)
pacman::p_load(
        ade4,
        cluster,
        corrplot,
        data.table,
        dplyr,
        fs,
        ggplot2,
        indicspecies,
        lubridate,
        magrittr,
        mapview,
        sf,
        stringr,
        tidyr,
        tmap,
        vegan
)
source("../helper_functions.R")
tmap_mode("view")
```

```{r CREATE OPTIONS}
#- What to load and what to compute
#- TRUE means load
options <- list(
  pre =      FALSE,
  distance = FALSE,
  mantel   = FALSE
)
```

```{r CREATE GLOBAL VARIABLES 1}
data.set = "biodrought"
all_seasons <- c("spring", "summer", "autumn", "winter")
seasons <- 1:3
```


```{r CREATE DA, LI and PU}
most.recent.data <- 
        dir_ls("../../data/combined_data/", regexp = "_core_taxa_data.rds") |> 
        str_remove("../../data/combined_data/03_") |> 
        str_remove("_core_taxa_data.rds") |> 
        ymd() |> 
        {\(x) x[which.max(x)]}()

data <- readRDS(file = paste0("../../data/combined_data/03_",most.recent.data,"_core_taxa_data.rds"))
da   <- lapply(data, function(x) x[data.set == "biodrought"])

da |> lapply(nrow)

seasons <- c(1,3)

#- create subset of least impacted sites
li <-
        lapply(seasons, function(x)
                da[[x]][fec.least.impacted == TRUE])
#- create subset of sites that are least impacted and removed from regional borders
pu <-
        lapply(1:2, function(x)
          li[[x]][illies_distance >= 25000 & bgr_distance >= 25000])
```

```{r PLOT MAPS}
map <- 
  rbindlist(da) |> 
  unique(by = "gr_sample_id") |> 
  st_as_sf()
tm_shape(map) + tm_dots() + tm_facets(by = "season")
```

```{r CHECK TYPOLOGIES, results = "hide"}
#- check how many instances of each type are there

map |> filter(season == "spring") |> pull(bgr) |> table()
map |> filter(season == "autumn") |> pull(bgr) |> table()
map |> filter(season == "spring") |> pull(illies) |> table()
map |> filter(season == "autumn") |> pull(illies) |> table()
map |> filter(season == "spring") |> pull(brt12) |> table()
map |> filter(season == "autumn") |> pull(brt12) |> table()

mean(c(nrow(da[[1]][is.na(species)])/nrow(da[[1]]), nrow(da[[3]][is.na(species)])/nrow(da[[3]])))
mean(c(nrow(da[[1]][is.na(genus)])/nrow(da[[1]]), nrow(da[[3]][is.na(genus)])/nrow(da[[3]])))
mean(c(nrow(da[[1]][is.na(family)])/nrow(da[[1]]), nrow(da[[3]][is.na(family)])/nrow(da[[3]])))

#- species missing at  33% of observations 
#- genus   missing at   4% of observations
#- family  missing at < 1% of observations

```

```{r GLOBAL VARIBLES 2}
seasons <- 1:2
da[[2]] <- da[[3]]
da[[3]] <- NULL
typologies <- c("brt12", "brt12_illies")
```

```{r RUN PRE2 AND 3}
if (!options$pre){ 

        das2 <- prep1(data = da,taxon = "species")
        dag2 <- prep1(data = da,taxon = "genus")
        daf2 <- prep1(data = da,taxon = "family")
        lis2 <- prep1(data = li,taxon = "species")
        lig2 <- prep1(data = li,taxon = "genus")
        lif2 <- prep1(data = li,taxon = "family")
        pus2 <- prep1(data = pu,taxon = "species")
        pug2 <- prep1(data = pu,taxon = "genus")
        puf2 <- prep1(data = pu,taxon = "family")
        das2.abu <- prep1(data = da, taxon = "species", abundance.to.pa = FALSE)
        dag2.abu <- prep1(data = da, taxon = "genus"  , abundance.to.pa = FALSE)
        daf2.abu <- prep1(data = da, taxon = "family" , abundance.to.pa = FALSE)
        
        das3 <- prep2(das2)
        lis3 <- prep2(lis2)
        pus3 <- prep2(pus2)
        dag3 <- prep2(dag2)
        lig3 <- prep2(lig2)
        pug3 <- prep2(pug2)
        daf3 <- prep2(daf2)
        lif3 <- prep2(lif2)
        puf3 <- prep2(puf2)
        das3.abu <- prep2(das2.abu) 
        dag3.abu <- prep2(dag2.abu) 
        daf3.abu <- prep2(daf2.abu) 
  
  saveRDS(
          object = list(
                  das2 = das2,
                  lis2 = lis2,
                  pus2 = pus2,
                  dag2 = dag2,
                  lig2 = lig2,
                  pug2 = pug2,
                  dag3 = dag3,
                  lig3 = lig3,
                  pug3 = pug3,
                  daf2 = daf2,
                  lif2 = lif2,
                  puf2 = puf2,
                  daf3 = daf3,
                  lif3 = lif3,
                  puf3 = puf3,
                  das3.abu = das3.abu,
                  dag3.abu = dag3.abu,
                  daf3.abu = daf3.abu
          ),
          
    file = paste0("auxilliary/pre_",data.set,".rds")
  )
} else if (options$pre){
  pre = readRDS(file = paste0("auxilliary/pre_",data.set,".rds"))
  for (i in seq_along(pre)){
    assign(x     = names(pre)[i], 
           value = pre[[i]])
  }
}
```

```{r check}
das2.abu[[1]] |> dplyr::select(!c("gr_sample_id", "brt12", "brt12_illies")) |> unlist() |> table()
daf2.abu[[1]] |> dplyr::select(!c("gr_sample_id", "brt12", "brt12_illies")) |> unlist() |> table()

das3.abu[[1]]  |> unlist() |> table()

```


```{r COMPUTE DISTANCE MATRICES}
# DISTANCE MATRIX  ------------------------------------------------------------------
if (!options$distance) {
  das.dist <- das3 |> prep3()
  lis.dist <- lig3 |> prep3()
  pus.dist <- pug3 |> prep3()
  dag.dist <- dag3 |> prep3()
  lig.dist <- lig3 |> prep3()
  pug.dist <- pug3 |> prep3()
  daf.dist <- daf3 |> prep3()
  lif.dist <- lif3 |> prep3()
  puf.dist <- puf3 |> prep3()
  das.abu.dist <- das3.abu |> prep3()
  dag.abu.dist <- dag3.abu |> prep3()
  daf.abu.dist <- daf3.abu |> prep3()

  saveRDS(
          object = list(
                  das.dist = das.dist,
                  lis.dist = lis.dist,
                  pus.dist = pus.dist,
                  dag.dist = dag.dist,
                  lig.dist = lig.dist,
                  pug.dist = pug.dist,
                  daf.dist = daf.dist,
                  lif.dist = lif.dist,
                  puf.dist = puf.dist,
                  das.abu.dist = das.abu.dist,
                  dag.abu.dist = dag.abu.dist,
                  daf.abu.dist = daf.abu.dist 
          ),
          file = paste0("auxilliary/distance_", data.set, ".rds")
  )
} else if (options$distance) {
  distance_list = readRDS(file = paste0("auxilliary/distance_", data.set, ".rds"))
  for (i in seq_along(distance_list)) {
    assign(x     = names(distance_list)[i],
           value = distance_list[[i]])
  }
}
```

```{r COMPUTE MANTEL TEST}
if (!options$mantel){
  
  seasons = 1:2
  #- species (abu) to species (pa)
  m1 <- lapply(seasons, function(x) mantel.rtest(das.dist[[x]], das.abu.dist[[x]]))
  #- species (abu) to genus (abu)
  m2 <- lapply(seasons, function(x) mantel.rtest(das.abu.dist[[x]], dag.abu.dist[[x]]))
  #- species (abu) to genus (pa)
  m3 <- lapply(seasons, function(x) mantel.rtest(das.abu.dist[[x]], dag.dist[[x]]))
  #- species (abu) to family (abu)
  m4 <- lapply(seasons, function(x) mantel.rtest(das.abu.dist[[x]], daf.abu.dist[[x]]))
  #- species (abu) to family (pa)
  m5 <- lapply(seasons, function(x) mantel.rtest(das.abu.dist[[x]], daf.dist[[x]]))
  #- species (pa) to genus (abu)
  m6 <- lapply(seasons, function(x) mantel.rtest(das.dist[[x]], dag.abu.dist[[x]]))
   #- species (PA) to genus (PA)
  m7 <- lapply(seasons, function(x) mantel.rtest(das.dist[[x]], dag.dist[[x]]))
  #- species (pa) to family (abu)
  m8 <- lapply(seasons, function(x) mantel.rtest(das.dist[[x]], daf.abu.dist[[x]]))
  #- species (PA) to family (PA)
  m9 <- lapply(seasons, function(x) mantel.rtest(das.dist[[x]], daf.dist[[x]]))
  #- genus (ABU) to genus (PA)
  m10 <- lapply(seasons, function(x) mantel.rtest(dag.abu.dist[[x]], dag.dist[[x]]))
  #- genus to family (ABU)
  m11 <- lapply(seasons, function(x) mantel.rtest(dag.abu.dist[[x]], daf.abu.dist[[x]]))
  #- genus (abu) to family (pa)
  m12 <- lapply(seasons, function(x) mantel.rtest(dag.abu.dist[[x]], daf.dist[[x]]))
  #- genus (pa) to family (abu)
  m13 <- lapply(seasons, function(x) mantel.rtest(dag.dist[[x]], daf.abu.dist[[x]]))
  #- genus (PA) to family (PA)
  m14 <- lapply(seasons, function(x) mantel.rtest(dag.dist[[x]], daf.dist[[x]]))
  #- family (ABU) to family (PA)
  m15 <- lapply(seasons, function(x) mantel.rtest(daf.abu.dist[[x]], daf.dist[[x]]))

  saveRDS(list(
    m1 = m1, 
    m2 = m2,
    m3 = m3,
    m4 = m4,
    m5 = m5,
    m6  = m6,
    m7  = m7,
    m8  = m8,
    m9  = m9,
    m10 = m10,
    m11 = m11,
    m12 = m12,
    m13 = m13,
    m14 = m14,
    m15 = m15
    ), 
    file = paste0("auxilliary/mantel_", data.set, ".rds"))
  
} else {
  mantel.list = readRDS(file = paste0("auxilliary/mantel_", data.set, ".rds"))
  for (i in seq_along(mantel.list)) {
    assign(x     = names(mantel.list)[i],
           value = mantel.list[[i]])
  }
}
```


```{r VISUALIZE MANTEL TEST}
#- correlation marices for each season 
mantel.spring <- matrix(0,nrow = 6, ncol = 6)
mantel.autumn <- matrix(0,nrow = 6, ncol = 6)
diag(mantel.spring) <- 1
diag(mantel.autumn) <- 1
tax.lvl <- c("species (abu)", "species (pa)","genus (abu)","genus (pa)", "family (abu)", "family (pa)")
rownames(mantel.spring) = colnames(mantel.spring) = tax.lvl
rownames(mantel.autumn) = colnames(mantel.autumn) = tax.lvl
from.vec <- rep(tax.lvl, times = c(5,4,3,2,1,0))
to.vec   <-  c( "species (pa)" ,"genus (abu)","genus (pa)" ,"family (abu)", "family (pa)",
                                "genus (abu)","genus (pa)" ,"family (abu)", "family (pa)",
                                              "genus (pa)" ,"family (abu)", "family (pa)",
                                                            "family (abu)", "family (pa)",
                                                                            "family (pa)")
for (i in 1:15){
        if (i == 1){
                statistic.vec <- vector(mode = "list", length = 15)
                p.value.vec   <- vector(mode = "list", length = 15)
        } 
        i.x <- get(paste0("m",i))
        statistic.vec[[i]] <- lapply(i.x, function(x) round(x$obs,3))
        p.value.vec[[i]]   <- lapply(i.x, function(x) round(x$pvalue,3))
} 

mantel.results <- data.table(
  from = rep(from.vec, each = 2),
  to   = rep(to.vec,   each = 2),
  statistic = unlist(statistic.vec),
  p.value   = unlist(p.value.vec),
  season = c("spring", "autumn")
)


#- loop over seasons 

for (i in 1:2){
 i.season <- c("spring", "autumn")[i]
 i.x      <- get(paste0("mantel.",i.season))
 for (k in 1:nrow(i.x)){ for (j in 1:ncol(i.x)){
     if (k == j) next()
     j.from = rownames(i.x)[k]; j.to   = colnames(i.x)[j]
     j.sub  = mantel.results[from == j.from & to == j.to & season == i.season, statistic]
     j.sub %<>% unlist()
     if (length(j.sub) == 0) {
       j.sub  = mantel.results[from == j.to & to == j.from & season == i.season, statistic]
       j.sub %<>% unlist()
       if (length(j.sub) == 0) next()
     }
     i.x[k,j] <- j.sub
     rm(list = ls()[grepl("^j\\.",ls())])
 }}
 assign(paste0("mantel.",i.season), i.x)
 rm(list = ls()[grepl("^i\\.",ls())])
}

corrplot(mantel.spring, 
         method = "shade", 
         type = "lower", 
         diag = FALSE, 
         addCoef.col = "black", 
         mar=c(0,0,1,0), 
         title = "spring", 
         tl.srt=0, 
         tl.col = "black", 
         tl.offset = 1, 
         col = viridisLite::rocket(n = 100))

corrplot(mantel.autumn, 
         method = "shade", 
         type = "lower", 
         diag = FALSE, 
         addCoef.col = "black", 
         mar=c(0,0,1,0), 
         title = "summer", 
         tl.srt=0, 
         tl.col = "black", 
         tl.offset = 1, 
         col = viridisLite::rocket(n = 100))

```