---
title: "Individual Data Set: Ebro basin"
author: "Jonathan Jupke"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(
        ade4,
        cluster,
        data.table,
        dplyr,
        ggplot2,
        indicspecies,
        magrittr,
        tidyr,
        vegan
)
source("../helper_functions.R")
```

```{r set options}
#- What to load and what to compute
#- TRUE means load
options <- list(
  pre =      TRUE,
  distance = TRUE,
  anosim =   TRUE,
  typical =  TRUE
)
```

```{r create global variables}
data.set = "ebro_basin"
all_seasons <- c("spring", "summer", "autumn", "winter")
seasons <- 1:3
typologies <- c("brt12")
```

```{r pre}
if (!options$pre){
  data <-
    readRDS("../../data/combined_data/01_2021-08-05_combined_data.rds")
  da <-
    lapply(data, function(x)
      x[data.set == "Ebro Hydrographic Confederation"])
  #- create subset of least impacted sites
  li <-
    lapply(seasons, function(x)
      da[[x]][fec.least.impacted == TRUE])
  #- create subset of sites that are least impacted and removed from regional borders
  pu <-
    lapply(seasons, function(x)
      li[[x]][illies_distance >= 25000 & bgr_distance >= 25000])
  
  #- check how many instances of each type are there 
  sapply(1:3, function(x)
    uniqueN(pu[[x]]$bgr))
  sapply(1:3, function(x)
    uniqueN(pu[[x]]$illies))
  sapply(1:3, function(x)
    uniqueN(pu[[x]]$brt12))
  
  daf2 <- prep1(data = da,
                taxon = "family" ,
                seasons = c(1:3))
  lif2 <- prep1(data = li,
                taxon = "family" ,
                seasons = c(1:3))
  puf2 <- prep1(data = pu,
                taxon = "family" ,
                seasons = c(1:3))
  # --- abundance --- #
  daf2_abu <- 
        prep1(
      data = da,
      taxon = "family",
      seasons = c(1:3),
      abundance.to.pa = FALSE
    )
  
  daf3 <- prep2(daf2)
  lif3 <- prep2(lif2)
  puf3 <- prep2(puf2)
  #--- abundance -- # 
  daf3_abu <- prep2(daf2_abu)
  
  saveRDS(
    object = list(daf2 = daf2,
                  lif2 = lif2, 
                  puf2 = puf2,
                  daf3 = daf3,
                  lif3 = lif3,
                  puf3 = puf3,
                  daf2_abu = daf2_abu, 
                  daf3_abu = daf3_abu
                  ), 
    file = paste0("auxilliary/pre_",data.set,".rds")
  )
} else if (options$pre){
  pre = readRDS(file = paste0("auxilliary/pre_",data.set,".rds"))
  for (i in seq_along(pre)){
    assign(x     = names(pre)[i], 
           value = pre[[i]])
  }
}
```

```{r distance_matrices}
# DISTANCE MATRIX  ------------------------------------------------------------------
if (!options$distance) {
  daf.dist <- daf3 |> prep3()
  lif.dist <- lif3 |> prep3()
  puf.dist <- puf3 |> prep3()
  daf.abu.dist <- daf3_abu |> prep3()

  saveRDS(
    object = list(
      daf.dist = daf.dist,
      lif.dist = lif.dist,
      puf.dist = puf.dist,
      daf.abu.dist = daf.abu.dist
    ),
    file = paste0("auxilliary/distance_", data.set, ".rds")
  )
} else if (options$distance) {
  distance_list = readRDS(file = paste0("auxilliary/distance_", data.set, ".rds"))
  for (i in seq_along(distance_list)) {
    assign(x     = names(distance_list)[i],
           value = distance_list[[i]])
  }
}
```

# Mantel Statistic

```{r mantel_statistic}

m_1 <- 
        lapply(1:3, function(x) mantel.rtest(daf.dist[[x]], daf.abu.dist[[x]])) |> 
        sapply(function(x) x$obs) |> 
        round(4)

```

The mantel correlations between abundance and presence/absence are `r m_1` on the family level are.

# Point biserial Correlation through indicspecies 

```{r PBC}
ivsaf <- ivs(data2 = daf2, data3 = daf3, season.data = 1:3, typologies = typologies, add = "all observations")
ivslf <- ivs(data2 = lif2, data3 = lif3, season.data = 1:3, typologies = typologies, add = "least impacted")
ivspf <- ivs(data2 = puf2, data3 = puf3, season.data = 1:3, typologies = typologies, add = "purified")

ivs_family  <- rbindlist(list(ivsaf, ivslf, ivspf))

ivs_family_mean  <- ivs_family[,mean(indval), by = c("typology", "type")]
ivs_family_mean[,c("taxon.level", "variable") := .("family" , "ivs_corr")]
```

```{r PBS plot}
ivs.plot1(ivs_family, taxon = "family")
```

# Classification Strength

```{r COMPUTE CLASSIFICATION STRENGTH}
csaf <- class.strength(data2 = daf2, data4 = daf.dist, season.data = 1:3, add = "all observations")
cslf <- class.strength(data2 = lif2, data4 = lif.dist, season.data = 1:3, add = "least impacted")
cspf <- class.strength(data2 = puf2, data4 = puf.dist, season.data = 1:3, add = "purified")

# saveRDS(object = list(csas,csag,csaf,csls,cslg,cslf,csps,cspg,cspf), 
#         "auxilliary/cs_german_monitoring.rds")

cs_family  <- rbindlist(list(csaf, cslf, cspf))

cs_family_mean  <- cs_family[,mean(cs), by = c("typology", "type")]
cs_family_mean[,c("taxon.level", "variable") := .("family" , "cs")]

```

```{r PLOT CLASSIFICATION STRENGTH}
class.strength.plot1(cs_family, taxon = "family")
class.strength.plot2(cs_family, taxon = "family")
class.strength.plot3(cs_family, taxon = "family")
```

# Silhouette Width 

```{r COMPUTE SILHOUETTES}
siaf <- wraper_silhouette(data2 = daf2, distance = daf.dist, add = "all observations")
silf <- wraper_silhouette(data2 = lif2, distance = lif.dist, add = "least impacted")
sipf <- wraper_silhouette(data2 = puf2, distance = puf.dist, add = "purified")
si_family  <- rbindlist(list(siaf, silf, sipf))
```


```{r PLOT SILHOUETTES}
silhouette.plot1(x = si_family, taxon = "family")
```

# ANOSIM 
```{r COMPUTE ANOSIM}
if (!options$anosim) {
        anaf <-
                wraper_anosim(
                        grouping = daf2,
                        distance = daf.dist,
                        permutations = 99,
                        add = "all observations"
                )
        anlf <-
                wraper_anosim(
                        grouping = lif2,
                        distance = lif.dist,
                        permutations = 99,
                        add = "least impacted"
                )
        anpf <-
                wraper_anosim(
                        grouping = puf2,
                        distance = puf.dist,
                        permutations = 99,
                        add = "purified"
                )
        
        saveRDS(
                object = list(
                        anaf = anaf,
                        anlf = anlf,
                        anpf = anpf
                ),
                file = paste0("auxilliary/anosim_", data.set, ".rds")
        )
} else if (options$anosim) {
        anosim.list = readRDS(file = paste0("auxilliary/anosim_", data.set, ".rds"))
        for (i in seq_along(anosim.list)) {
                assign(x     = names(anosim.list)[i],
                       value = anosim.list[[i]])
        }
}



an_family  <- rbindlist(list(anaf, anlf, anpf))
an_family_mean  <- an_family[, mean(R), by = c("typology", "type")]
an_family_mean[, c("taxon.level", "variable") := .("family" , "Anosim R")]
```


```{r PLOT ANOSIM}
anosim.plot1(x = an_family, taxon = "family")
```

# Indicator and Typical taxa
```{r analysis TYPICAL TAXA}
if (!options$typical){
        isaf <-
                indicator_analysis(
                        data2 = daf2,
                        data3 = daf3,
                        B.lvl = 0.66,
                        add = "all observations"
                )
        islf <-
                indicator_analysis(
                        data2 = lif2,
                        data3 = lif3,
                        B.lvl = 0.66,
                        add = "least impacted"
                )
        ispf <-
                indicator_analysis(
                        data2 = puf2,
                        data3 = puf3,
                        B.lvl = 0.66,
                        add = "purified"
                )

        saveRDS(
                object = list(isaf = isaf,
                              islf = islf,
                              ispf = ispf),
                file = paste0("auxilliary/indi_typ_", data.set, ".rds")
        )
} else if (options$typical) {
        typical.list <- readRDS(file = paste0("auxilliary/indi_typ_", data.set, ".rds"))
        for (i in seq_along(typical.list)) {
                assign(x     = names(typical.list)[i],
                       value = typical.list[[i]])
        }
}

jac.fam <- rbindlist(list(jaccard_extract(isaf),jaccard_extract(islf),jaccard_extract(ispf)))
mid.fam <- rbindlist(list(mid_extract(isaf),mid_extract(islf),mid_extract(ispf)))
```


```{r PLOT TYPICAL TAXA}
jaccard_plot(jac.fam, "family")
mid_plot(mid.fam, "family")
```

```{r create summary table}
summary.out <- rbindlist(
        list(
        
                an_family_mean,
                
                an_family_mean,
                
                ivs_family_mean,
                
                ivs_family_mean,
         
                cs_family_mean,
       
                cs_family_mean
        )
)
fwrite(summary.out, file = paste0(data.set,".csv"))
```

