---
title: "GLD"
author: "Jonathan Jupke"
date: "13 8 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
pacman::p_load(
        ade4,
        cluster,
        data.table,
        dplyr,
        ggplot2,
        indicspecies,
        magrittr,
        tidyr,
        vegan
)
source("../helper_functions.R")
```


```{r echo = F}
data.set = "gld"
data <- readRDS("../../data/combined_data/01_2021-08-05_combined_data.rds")
data <- lapply(data, function(x) x[data.set == "German federal monitoring data from Saxony Anhalt"])
all_seasons <- c("spring", "summer", "autumn", "winter")
seasons <- 1:3
da <- lapply(seasons, function(x) data[[x]][!is.na(german_type)])
#- create subset of least impacted sites  
li <- lapply(seasons, function(x) data[[x]][fec.least.impacted == TRUE])
#- create subset of sites that are least impacted and removed from regional borders 
pu <- lapply(seasons, function(x) data[[x]][illies_distance >= 25000 & bgr_distance >= 25000])
```

```{r}
sapply(1:3, function(x) uniqueN(pu[[x]]$bgr))
sapply(1:3, function(x) uniqueN(pu[[x]]$illies))
sapply(1:3, function(x) uniqueN(pu[[x]]$brt12))
sapply(1:3, function(x) uniqueN(pu[[x]]$german_typ))
typologies <- c("brt12", "german_type")
```
```{r echo = F}
das2 <- prep1(data = da, taxon = "species", seasons = c(1:3)) 
lis2 <- prep1(data = li, taxon = "species", seasons = c(1:3)) 
pus2 <- prep1(data = pu, taxon = "species", seasons = c(1:3)) 
dag2 <- prep1(data = da, taxon = "genus"  , seasons = c(1:3)) 
lig2 <- prep1(data = li, taxon = "genus"  , seasons = c(1:3)) 
pug2 <- prep1(data = pu, taxon = "genus"  , seasons = c(1:3)) 
daf2 <- prep1(data = da, taxon = "family" , seasons = c(1:3)) 
lif2 <- prep1(data = li, taxon = "family" , seasons = c(1:3)) 
puf2 <- prep1(data = pu, taxon = "family" , seasons = c(1:3)) 

das3 <- prep2(das2)
lis3 <- prep2(lis2)
pus3 <- prep2(pus2)
dag3 <- prep2(dag2)
lig3 <- prep2(lig2)
pug3 <- prep2(pug2)
daf3 <- prep2(daf2)
lif3 <- prep2(lif2)
puf3 <- prep2(puf2)

# DISTANCE MATRIX  ------------------------------------------------------------------

das.dist <- das3 |> prep3()
lis.dist <- lis3 |> prep3()
pus.dist <- pus3 |> prep3()
dag.dist <- dag3 |> prep3()
lig.dist <- lig3 |> prep3()
pug.dist <- pug3 |> prep3()
daf.dist <- daf3 |> prep3()
lif.dist <- lif3 |> prep3()
puf.dist <- puf3 |> prep3()
```

# Manetel Statistic

```{r echo = F}
m1 <- lapply(1:3, function(x) mantel.rtest(das.dist[[x]], dag.dist[[x]]))
m2 <- lapply(1:3, function(x) mantel.rtest(das.dist[[x]], daf.dist[[x]]))
m1 <- sapply(m1, function(x) x$obs)
m2 <- sapply(m2, function(x) x$obs)
```

The mantel correlation between species and genus level are `r m1`. Between species and family level they are `r m2`.

# Correlation 

```{r echo = F}
ivsas <- ivs(data2 = das2, data3 = das3, season.data = 1:3, typologies = typologies, add = "all observations")
ivsag <- ivs(data2 = dag2, data3 = dag3, season.data = 1:3, typologies = typologies, add = "all observations")
ivsaf <- ivs(data2 = daf2, data3 = daf3, season.data = 1:3, typologies = typologies, add = "all observations")
ivsls <- ivs(data2 = lis2, data3 = lis3, season.data = 1:3, typologies = typologies, add = "least impacted")
ivslg <- ivs(data2 = lig2, data3 = lig3, season.data = 1:3, typologies = typologies, add = "least impacted")
ivslf <- ivs(data2 = lif2, data3 = lif3, season.data = 1:3, typologies = typologies, add = "least impacted")
ivsps <- ivs(data2 = pus2, data3 = pus3, season.data = 1:3, typologies = typologies, add = "purified")
ivspg <- ivs(data2 = pug2, data3 = pug3, season.data = 1:3, typologies = typologies, add = "purified")
ivspf <- ivs(data2 = puf2, data3 = puf3, season.data = 1:3, typologies = typologies, add = "purified")

ivs_species <- rbindlist(list(ivsas, ivsls, ivsps))
ivs_genus   <- rbindlist(list(ivsag, ivslg, ivspg))
ivs_family  <- rbindlist(list(ivsaf, ivslf, ivspf))

ivs_species_mean <- ivs_species[,mean(indval), by = c("typology", "type")]
ivs_genus_mean   <- ivs_species[,mean(indval), by = c("typology", "type")]
ivs_family_mean  <- ivs_species[,mean(indval), by = c("typology", "type")]
ivs_species_mean[,c("taxon.level", "variable") := .("species", "ivs_corr")]
  ivs_genus_mean[,c("taxon.level", "variable") := .("genus"  , "ivs_corr")]
 ivs_family_mean[,c("taxon.level", "variable") := .("family" , "ivs_corr")]
```

```{r echo =F }
ivs.plot1(ivs_species, taxon = "species")
ivs.plot1(ivs_genus, taxon = "genus")
ivs.plot1(ivs_family, taxon = "family")
```

# Classification Strength

```{r}
csas <- class.strength(data2 = das2, data4 = das.dist, season.data = 1:3, add = "all observations")
csag <- class.strength(data2 = dag2, data4 = dag.dist, season.data = 1:3, add = "all observations")
csaf <- class.strength(data2 = daf2, data4 = daf.dist, season.data = 1:3, add = "all observations")
csls <- class.strength(data2 = lis2, data4 = lis.dist, season.data = 1:3, add = "least impacted")
cslg <- class.strength(data2 = lig2, data4 = lig.dist, season.data = 1:3, add = "least impacted")
cslf <- class.strength(data2 = lif2, data4 = lif.dist, season.data = 1:3, add = "least impacted")
csps <- class.strength(data2 = pus2, data4 = pus.dist, season.data = 1:3, add = "purified")
cspg <- class.strength(data2 = pug2, data4 = pug.dist, season.data = 1:3, add = "purified")
cspf <- class.strength(data2 = puf2, data4 = puf.dist, season.data = 1:3, add = "purified")

cs_species <- rbindlist(list(csas, csls, csps))
cs_genus   <- rbindlist(list(csag, cslg, cspg))
cs_family  <- rbindlist(list(csaf, cslf, cspf))

cs_species_mean <- cs_species[,mean(cs), by = c("typology", "type")]
cs_genus_mean   <- cs_genus[,mean(cs), by = c("typology", "type")]
cs_family_mean  <- cs_family[,mean(cs), by = c("typology", "type")]
cs_species_mean[,c("taxon.level", "variable") := .("species", "cs")]
cs_genus_mean[,c("taxon.level", "variable") := .("genus"  , "cs")]
cs_family_mean[,c("taxon.level", "variable") := .("family" , "cs")]

```

```{r}
class.strength.plot1(cs_species, taxon = "species")
class.strength.plot1(cs_genus, taxon = "genus")
class.strength.plot1(cs_family, taxon = "family")
class.strength.plot2(cs_species, taxon = "species")
class.strength.plot2(cs_genus, taxon = "genus")
class.strength.plot2(cs_family, taxon = "family")
class.strength.plot3(cs_species, taxon = "species")
class.strength.plot3(cs_genus, taxon = "genus")
class.strength.plot3(cs_family, taxon = "family")
```

# Silhouette Width 

```{r}
sias <- wraper_silhouette(data2 = das2, distance = das.dist, add = "all observations")
sias <- wraper_silhouette(data2 = das2, distance = das.dist, add = "all observations")
siag <- wraper_silhouette(data2 = dag2, distance = dag.dist, add = "all observations")
siaf <- wraper_silhouette(data2 = daf2, distance = daf.dist, add = "all observations")
sils <- wraper_silhouette(data2 = lis2, distance = lis.dist, add = "least impacted")
silg <- wraper_silhouette(data2 = lig2, distance = lig.dist, add = "least impacted")
silf <- wraper_silhouette(data2 = lif2, distance = lif.dist, add = "least impacted")
sips <- wraper_silhouette(data2 = pus2, distance = pus.dist, add = "purified")
sipg <- wraper_silhouette(data2 = pug2, distance = pug.dist, add = "purified")
sipf <- wraper_silhouette(data2 = puf2, distance = puf.dist, add = "purified")

si_species <- rbindlist(list(sias, sils, sips))
si_genus   <- rbindlist(list(siag, silg, sipg))
si_family  <- rbindlist(list(siaf, silf, sipf))
```


```{r}
silhouette.plot1(x = si_species, taxon = "species")
silhouette.plot1(x = si_genus, taxon = "genus")
silhouette.plot1(x = si_family, taxon = "family")
```

# ANOSIM 
```{r}
anas <- wraper_anosim(grouping = das2, distance = das.dist, permutations = 99, add = "all observations")
anas <- wraper_anosim(grouping = das2, distance = das.dist, permutations = 99, add = "all observations")
anag <- wraper_anosim(grouping = dag2, distance = dag.dist, permutations = 99, add = "all observations")
anaf <- wraper_anosim(grouping = daf2, distance = daf.dist, permutations = 99, add = "all observations")
anls <- wraper_anosim(grouping = lis2, distance = lis.dist, permutations = 99, add = "least impacted")
anlg <- wraper_anosim(grouping = lig2, distance = lig.dist, permutations = 99, add = "least impacted")
anlf <- wraper_anosim(grouping = lif2, distance = lif.dist, permutations = 99, add = "least impacted")
anps <- wraper_anosim(grouping = pus2, distance = pus.dist, permutations = 99, add = "purified")
anpg <- wraper_anosim(grouping = pug2, distance = pug.dist, permutations = 99, add = "purified")
anpf <- wraper_anosim(grouping = puf2, distance = puf.dist, permutations = 99, add = "purified")

an_species <- rbindlist(list(anas, anls, anps))
an_genus   <- rbindlist(list(anag, anlg, anpg))
an_family  <- rbindlist(list(anaf, anlf, anpf))

an_species_mean <- an_species[,mean(R), by = c("typology", "type")]
an_genus_mean   <- an_genus[,mean(R), by = c("typology", "type")]
an_family_mean  <- an_family[,mean(R), by = c("typology", "type")]
an_species_mean[,c("taxon.level", "variable") := .("species", "Anosim R")]
an_genus_mean[,c("taxon.level", "variable") := .("genus"  , "Anosim R")]
an_family_mean[,c("taxon.level", "variable") := .("family" , "Anosim R")]
```


```{r}
anosim.plot1(x = an_species, taxon = "species")
anosim.plot1(x = an_genus, taxon = "genus")
anosim.plot1(x = an_family, taxon = "family")
```

# Indicator and Typical taxa
```{r}
isas <- indicator_analysis(data3 = das3, data2 = das2, B.lvl = 0.33, add = "all observations")
isag <- indicator_analysis(data2 = dag2, data3 = dag3, B.lvl = 0.50, add = "all observations")
isaf <- indicator_analysis(data2 = daf2, data3 = daf3, B.lvl = 0.66, add = "all observations")
isls <- indicator_analysis(data2 = lis2, data3 = lis3, B.lvl = 0.33, add = "least impacted")
islg <- indicator_analysis(data2 = lig2, data3 = lig3, B.lvl = 0.50, add = "least impacted")
islf <- indicator_analysis(data2 = lif2, data3 = lif3, B.lvl = 0.66, add = "least impacted")
isps <- indicator_analysis(data2 = pus2, data3 = pus3, B.lvl = 0.33, add = "purified")
ispg <- indicator_analysis(data2 = pug2, data3 = pug3, B.lvl = 0.50, add = "purified")
ispf <- indicator_analysis(data2 = puf2, data3 = puf3, B.lvl = 0.66, add = "purified")

jac.spe <- rbindlist(list(jaccard_extract(isas),jaccard_extract(isls),jaccard_extract(isps)))
jac.gen <- rbindlist(list(jaccard_extract(isag),jaccard_extract(islg),jaccard_extract(ispg)))
jac.fam <- rbindlist(list(jaccard_extract(isaf),jaccard_extract(islf),jaccard_extract(ispf)))
mid.spe <- rbindlist(list(mid_extract(isas),mid_extract(isls),mid_extract(isps)))
mid.gen <- rbindlist(list(mid_extract(isag),mid_extract(islg),mid_extract(ispg)))
mid.fam <- rbindlist(list(mid_extract(isaf),mid_extract(islf),mid_extract(ispf)))
```


```{r}
jaccard_plot(jac.spe, "species")
jaccard_plot(jac.gen, "genus")
jaccard_plot(jac.fam, "family")
mid_plot(mid.spe, "species")
mid_plot(mid.gen, "genus")
mid_plot(mid.fam, "family")
```

```{r}
summary.out <- rbindlist(
        list(
                an_species_mean,
                an_genus_mean,
                an_family_mean,
                an_species_mean,
                an_genus_mean,
                an_family_mean,
                ivs_species_mean,
                ivs_genus_mean,
                ivs_family_mean,
                ivs_species_mean,
                ivs_genus_mean,
                ivs_family_mean,
                cs_species_mean,
                cs_genus_mean,
                cs_family_mean,
                cs_species_mean,
                cs_genus_mean,
                cs_family_mean
        )
)
fwrite(summary.out, file = "gld.csv")
        ```

