---
title: 'Individual data sets: Monitoring Greece'
author: "Jonathan Jupke"
output: html_document
---

This data set can not be used for any individual evaluations.

```{r SETUP, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning=FALSE)
pacman::p_load(
        ade4,
        cluster,
        corrplot,
        data.table,
        dplyr,
        ggplot2,
        indicspecies,
        magrittr,
        mapview,
        sf,
        tidyr,
        tmap,
        vegan
)
source("../helper_functions.R")
tmap_mode("view")
```

```{r CREATE OPTIONS}
#- What to load and what to compute
#- TRUE means load
options <- list(
  pre =      TRUE,
  distance = TRUE,
  mantel   = TRUE
)
```


```{r CREATE GLOBAL VARIABLES 1}
data.set = "monitoring_greece"
all_seasons <- c("spring", "summer", "autumn", "winter")
seasons <- 1:3
```


```{r CREATE DA, LI and PU}
most.recent.data <- 
        fs::dir_ls("../../data/combined_data/", regexp = "_core_taxa_data.rds") |> 
        stringr::str_remove("../../data/combined_data/03_") |> 
        stringr::str_remove("_core_taxa_data.rds") |> 
        lubridate::ymd() |> 
        {\(x) x[which.max(x)]}()

data <-
        readRDS(
                file = 
                        paste0(
                                "../../data/combined_data/03_",
                                most.recent.data,
                                "_core_taxa_data.rds"
                                )
                )
da <-
        lapply(data, function(x)
                x[data.set == "Monitoring data from Greece"])
lapply(da, nrow)
da <- da[2]
#- create subset of least impacted sites
li <-
        lapply(1, function(x)
                da[[x]][fec.least.impacted == TRUE])
#- create subset of sites that are least impacted and removed from regional borders
pu <-
        lapply(1, function(x)
                li[[x]][illies_distance >= 25000 & bgr_distance >= 25000])
```

```{r PLOT MAPS}
map <- 
  rbindlist(li) |> 
  unique(by = "gr_sample_id") |> 
  st_as_sf()
tm_shape(map) + tm_dots(col = "brt12") + tm_facets(by = "season")
```


```{r CHECK TYPOLOGIES, results = "hide"}
#- check how many instances of each type are there


map |> filter(season == "summer") |> pull(bgr) |> table()
map |> filter(season == "summer") |> pull(illies) |> table()
map |> filter(season == "summer") |> pull(brt12) |> table()

#- comparisons dont make sense for any

c(nrow(da[[1]][is.na(species)])/nrow(da[[1]]))
c(nrow(da[[1]][is.na(genus)])  /nrow(da[[1]]))
c(nrow(da[[1]][is.na(family)]) /nrow(da[[1]]))

#- only family data avialable 
```

```{r GLOBAL VARIBLES 2}
seasons <- 1:3
typologies <- c("brt12")
```


```{r RUN PRE2 AND 3}
if (!options$pre){ 
        das2 <- prep1(data = da,
                      taxon = "species")
        dag2 <- prep1(data = da,
                      taxon = "genus")
        daf2 <- prep1(data = da,
                      taxon = "family")
        lis2 <- prep1(data = li,
                      taxon = "species")
        lig2 <- prep1(data = li,
                      taxon = "genus")
        lif2 <- prep1(data = li,
                      taxon = "family")
        pus2 <- prep1(data = pu,
                      taxon = "species")
        pug2 <- prep1(data = pu,
                      taxon = "genus")
        puf2 <- prep1(data = pu,
                      taxon = "family")
        lis2.abu <-
                prep1(data = li,
                      taxon = "species",
                      abundance.to.pa = FALSE)
        lig2.abu <-
                prep1(data = li,
                      taxon = "genus",
                      abundance.to.pa = FALSE)
        lif2.abu <-
                prep1(data = li,
                      taxon = "family",
                      abundance.to.pa = FALSE)
        
  das3 <- prep2(das2)
  lis3 <- prep2(lis2)
  pus3 <- prep2(pus2)
  dag3 <- prep2(dag2)
  lig3 <- prep2(lig2)
  pug3 <- prep2(pug2)
  daf3 <- prep2(daf2)
  lif3 <- prep2(lif2)
  puf3 <- prep2(puf2)
  lis3.abu <- prep2(lis2.abu) 
  lig3.abu <- prep2(lig2.abu) 
  lif3.abu <- prep2(lif2.abu) 
  
   saveRDS(
          object = list(
                  das2 = das2,
                  lis2 = lis2,
                  pus2 = pus2,
                  dag2 = dag2,
                  lig2 = lig2,
                  pug2 = pug2,
                  dag3 = dag3,
                  lig3 = lig3,
                  pug3 = pug3,
                  daf2 = daf2,
                  lif2 = lif2,
                  puf2 = puf2,
                  daf3 = daf3,
                  lif3 = lif3,
                  puf3 = puf3,
                  lis3.abu = lis3.abu,
                  lig3.abu = lig3.abu,
                  lif3.abu = lif3.abu
          ),
          
    file = paste0("auxilliary/pre_",data.set,".rds")
  )
  
} else if (options$pre){
  pre = readRDS(file = paste0("auxilliary/pre_",data.set,".rds"))
  for (i in seq_along(pre)){
    assign(x     = names(pre)[i], 
           value = pre[[i]])
  }
}
```

```{r COMPUTE DISTANCE MATRICES}
# DISTANCE MATRIX  ------------------------------------------------------------------
if (!options$distance) {
  das.dist <- dag3 |> prep3()
  lis.dist <- lig3 |> prep3()
  pus.dist <- pug3 |> prep3()
  dag.dist <- dag3 |> prep3()
  lig.dist <- lig3 |> prep3()
  pug.dist <- pug3 |> prep3()
  daf.dist <- daf3 |> prep3()
  lif.dist <- lif3 |> prep3()
  puf.dist <- puf3 |> prep3()
  lis.abu.dist <- lig3.abu |> prep3()
  lig.abu.dist <- lig3.abu |> prep3()
  lif.abu.dist <- lif3.abu |> prep3()

  saveRDS(
          object = list(
                  dag.dist = dag.dist,
                  lig.dist = lig.dist,
                  pug.dist = pug.dist,
                  daf.dist = daf.dist,
                  lif.dist = lif.dist,
                  puf.dist = puf.dist,
                  lig.abu.dist = lig.abu.dist,
                  lif.abu.dist = lif.abu.dist 
          ),
          file = paste0("auxilliary/distance_", data.set, ".rds")
  )
} else if (options$distance) {
  distance_list = readRDS(file = paste0("auxilliary/distance_", data.set, ".rds"))
  for (i in seq_along(distance_list)) {
    assign(x     = names(distance_list)[i],
           value = distance_list[[i]])
  }
}
```

# Mantel test 
                
```{r COMPUTE MANTEL TEST}
if (!options$mantel){
  
  
  #- species (abu) to species (pa)
  m1 <- lapply(1:3, function(x) mantel.rtest(lis.dist[[x]], lis.abu.dist[[x]]))
  #- species (abu) to genus (abu)
  m2 <- lapply(1:3, function(x) mantel.rtest(lis.abu.dist[[x]], lig.abu.dist[[x]]))
  #- species (abu) to genus (pa)
  m3 <- lapply(1:3, function(x) mantel.rtest(lis.abu.dist[[x]], lig.dist[[x]]))
  #- species (abu) to family (abu)
  m4 <- lapply(1:3, function(x) mantel.rtest(lis.abu.dist[[x]], lif.abu.dist[[x]]))
  #- species (abu) to family (pa)
  m5 <- lapply(1:3, function(x) mantel.rtest(lis.abu.dist[[x]], lif.dist[[x]]))
  #- species (pa) to genus (abu)
  m6 <- lapply(1:3, function(x) mantel.rtest(lis.dist[[x]], lig.abu.dist[[x]]))
  #- species (PA) to genus (PA)
  m7 <- lapply(1:3, function(x) mantel.rtest(lis.dist[[x]], lig.dist[[x]]))
  #- species (pa) to family (abu)
  m8 <- lapply(1:3, function(x) mantel.rtest(lis.dist[[x]], lif.abu.dist[[x]]))
  #- species (PA) to family (PA)
  m9 <- lapply(1:3, function(x) mantel.rtest(lis.dist[[x]], lif.dist[[x]]))
  #- genus (ABU) to genus (PA)
  m10 <- lapply(1:3, function(x) mantel.rtest(lig.abu.dist[[x]], lig.dist[[x]]))
  #- genus to family (ABU)
  m11 <- lapply(1:3, function(x) mantel.rtest(lig.abu.dist[[x]], lif.abu.dist[[x]]))
  #- genus (abu) to family (pa)
  m12 <- lapply(1:3, function(x) mantel.rtest(lig.abu.dist[[x]], lif.dist[[x]]))
  #- genus (pa) to family (abu)
  m13 <- lapply(1:3, function(x) mantel.rtest(lig.dist[[x]], lif.abu.dist[[x]]))
  #- genus (PA) to family (PA)
  m14 <- lapply(1:3, function(x) mantel.rtest(lig.dist[[x]], lif.dist[[x]]))
  #- family (ABU) to family (PA)
  m15 <- lapply(1:3, function(x) mantel.rtest(lif.abu.dist[[x]], lif.dist[[x]]))

  saveRDS(list(
    m1 = m1, 
    m2 = m2,
    m3 = m3,
    m4 = m4,
    m5 = m5,
    m6  = m6,
    m7  = m7,
    m8  = m8,
    m9  = m9,
    m10 = m10,
    m11 = m11,
    m12 = m12,
    m13 = m13,
    m14 = m14,
    m15 = m15
    ), 
    file = paste0("auxilliary/mantel_", data.set, ".rds"))
  
} else {
  mantel.list = readRDS(file = paste0("auxilliary/mantel_", data.set, ".rds"))
  for (i in seq_along(mantel.list)) {
    assign(x     = names(mantel.list)[i],
           value = mantel.list[[i]])
  }
}  

#- correlation marices for each season 
mantel.spring <- matrix(0,nrow = 6, ncol = 6)
mantel.summer <- matrix(0,nrow = 6, ncol = 6)
mantel.autumn <- matrix(0,nrow = 6, ncol = 6)
diag(mantel.spring) <- 1
diag(mantel.summer) <- 1
diag(mantel.autumn) <- 1
tax.lvl <- c("species (abu)", "species (pa)","genus (abu)","genus (pa)", "family (abu)", "family (pa)")
rownames(mantel.spring) = colnames(mantel.spring) = tax.lvl
rownames(mantel.summer) = colnames(mantel.summer) = tax.lvl
rownames(mantel.autumn) = colnames(mantel.autumn) = tax.lvl
from.vec <- rep(tax.lvl, times = c(5,4,3,2,1,0))

mantel.results <- data.table(
  from = rep(from.vec, each = 3),
  to   = rep(c(
    "species (pa)" ,"genus (abu)","genus (pa)" ,"family (abu)", "family (pa)",
                    "genus (abu)","genus (pa)" ,"family (abu)", "family (pa)",
                                  "genus (pa)" ,"family (abu)", "family (pa)",
                                                "family (abu)", "family (pa)",
                                                                "family (pa)"),
    each = 3),
  statistic = c(
    lapply(m1, function(x) round(x$obs,3)), 
    lapply(m2, function(x) round(x$obs,3)), 
    lapply(m3, function(x) round(x$obs,3)), 
    lapply(m4, function(x) round(x$obs,3)),
    lapply(m5, function(x) round(x$obs,3)),
    lapply(m6, function(x) round(x$obs,3)),
    lapply(m7, function(x) round(x$obs,3)), 
    lapply(m8, function(x) round(x$obs,3)), 
    lapply(m9, function(x) round(x$obs,3)), 
    lapply(m10, function(x) round(x$obs,3)),
    lapply(m11, function(x) round(x$obs,3)),
    lapply(m12, function(x) round(x$obs,3)),
    lapply(m13, function(x) round(x$obs,3)),
    lapply(m14, function(x) round(x$obs,3)),
    lapply(m15, function(x) round(x$obs,3))
    ),
  p.value   = c(
    lapply(m1, function(x) round(x$pvalue,3)), 
    lapply(m2, function(x) round(x$pvalue,3)), 
    lapply(m3, function(x) round(x$pvalue,3)), 
    lapply(m4, function(x) round(x$pvalue,3)),
    lapply(m5, function(x) round(x$pvalue,3)),
    lapply(m6, function(x) round(x$pvalue,3)),
    lapply(m7, function(x) round(x$pvalue,3)),
    lapply(m8, function(x) round(x$pvalue,3)),
    lapply(m9, function(x) round(x$pvalue,3)),
    lapply(m10, function(x) round(x$pvalue,3)),
    lapply(m11, function(x) round(x$pvalue,3)),
    lapply(m12, function(x) round(x$pvalue,3)),
    lapply(m13, function(x) round(x$pvalue,3)),
    lapply(m14, function(x) round(x$pvalue,3)),
    lapply(m15, function(x) round(x$pvalue,3))
    ),
  season = c("spring", "summer", "autumn")
)
#- loop over seasons 
for (i in 1:3){
 i.season <- c("spring", "summer", "autumn")[i]
 i.x      <- get(paste0("mantel.",i.season))
 for (k in 1:nrow(i.x)){ for (j in 1:ncol(i.x)){
     if (k == j) next()
     j.from = rownames(i.x)[k]; j.to   = colnames(i.x)[j]
     j.sub  = mantel.results[from == j.from & to == j.to & season == i.season, statistic]
     j.sub %<>% unlist()
     if (is.null(j.sub)) {
       j.sub  = mantel.results[from == j.to & to == j.from & season == i.season, statistic]
       j.sub %<>% unlist()
       if (is.null(j.sub)) next()
     }
     i.x[k,j] <- j.sub
     rm(list = ls()[grepl("^j\\.",ls())])
 }}
 assign(paste0("mantel.",i.season), i.x)
 rm(list = ls()[grepl("^i\\.",ls())])
}

corrplot(
        mantel.spring,
        method = "shade",
        type = "lower",
        diag = FALSE,
        addCoef.col = "black",
        mar = c(0, 0, 1, 0),
        title = "spring",
        tl.srt = 0,
        tl.col = "black",
        tl.offset = 1,
        col = viridisLite::rocket(n = 100)
)
corrplot(
        mantel.summer,
        method = "shade",
        type = "lower",
        diag = FALSE,
        addCoef.col = "black",
        mar = c(0, 0, 1, 0),
        title = "spring",
        tl.srt = 0,
        tl.col = "black",
        tl.offset = 1,
        col = viridisLite::rocket(n = 100)
)
corrplot(
        mantel.autumn,
        method = "shade",
        type = "lower",
        diag = FALSE,
        addCoef.col = "black",
        mar = c(0, 0, 1, 0),
        title = "spring",
        tl.srt = 0,
        tl.col = "black",
        tl.offset = 1,
        col = viridisLite::rocket(n = 100)
)


```





# Point biserial Correlation through indicspecies 

```{r PBC}
ivsaf <- ivs(data2 = daf2, data3 = daf3, season.data = seasons, typologies = typologies, add = "all observations")
ivslf <- ivs(data2 = lif2, data3 = lif3, season.data = seasons, typologies = typologies, add = "least impacted")
ivspf <- ivs(data2 = puf2, data3 = puf3, season.data = seasons, typologies = typologies, add = "purified")

ivs_family  <- rbindlist(list(ivsaf, ivslf, ivspf))

ivs_family_mean  <- ivs_family[,mean(indval), by = c("typology", "type")]
ivs_family_mean[,c("taxon.level", "variable") := .("family" , "ivs_corr")]
```

```{r PBS plot}
ivs.plot1(ivs_family, taxon = "family")
```

# Classification Strength

```{r COMPUTE CLASSIFICATION STRENGTH}
csaf <- class.strength(data2 = daf2, data4 = daf.dist, season.data = seasons, add = "all observations")
cslf <- class.strength(data2 = lif2, data4 = lif.dist, season.data = seasons, add = "least impacted")
cspf <- class.strength(data2 = puf2, data4 = puf.dist, season.data = seasons, add = "purified")

# saveRDS(object = list(csas,csag,csaf,csls,cslg,cslf,csps,cspg,cspf), 
#         "auxilliary/cs_german_monitoring.rds")

cs_family  <- rbindlist(list(csaf, cslf, cspf))

cs_family_mean  <- cs_family[,mean(cs), by = c("typology", "type")]
cs_family_mean[,c("taxon.level", "variable") := .("family" , "cs")]

```

```{r PLOT CLASSIFICATION STRENGTH}
class.strength.plot1(cs_family, taxon = "family")
class.strength.plot2(cs_family, taxon = "family")
class.strength.plot3(cs_family, taxon = "family")
```

# Silhouette Width 

```{r COMPUTE SILHOUETTES}
siaf <- wraper_silhouette(data2 = daf2, distance = daf.dist, add = "all observations")
silf <- wraper_silhouette(data2 = lif2, distance = lif.dist, add = "least impacted")
#sipf <- wraper_silhouette(data2 = puf2, distance = puf.dist, add = "purified")
si_family  <- rbindlist(list(siaf, silf))
```


```{r PLOT SILHOUETTES}
silhouette.plot1(x = si_family, taxon = "family")
```

# ANOSIM 
```{r COMPUTE ANOSIM}
if (!options$anosim) {
        anaf <-
                wraper_anosim(
                        grouping = daf2,
                        distance = daf.dist,
                        permutations = 99,
                        add = "all observations"
                )
        anlf <-
                wraper_anosim(
                        grouping = lif2,
                        distance = lif.dist,
                        permutations = 99,
                        add = "least impacted"
                )
        # anpf <-
        #         wraper_anosim(
        #                 grouping = puf2,
        #                 distance = puf.dist,
        #                 permutations = 99,
        #                 add = "purified"
        #         )
        # 
        saveRDS(
                object = list(
                        anaf = anaf,
                        anlf = anlf
                ),
                file = paste0("auxilliary/anosim_", data.set, ".rds")
        )
} else if (options$anosim) {
        anosim.list = readRDS(file = paste0("auxilliary/anosim_", data.set, ".rds"))
        for (i in seq_along(anosim.list)) {
                assign(x     = names(anosim.list)[i],
                       value = anosim.list[[i]])
        }
}



an_family  <- rbindlist(list(anaf, anlf))
an_family_mean  <- an_family[, mean(R), by = c("typology", "type")]
an_family_mean[, c("taxon.level", "variable") := .("family" , "Anosim R")]
```


```{r PLOT ANOSIM}
anosim.plot1(x = an_family, taxon = "family")
```

# Indicator and Typical taxa
```{r analysis TYPICAL TAXA}
if (!options$typical){
        isaf <-
                indicator_analysis(
                        data2 = daf2,
                        data3 = daf3,
                        B.lvl = 0.66,
                        add = "all observations"
                )
        islf <-
                indicator_analysis(
                        data2 = lif2,
                        data3 = lif3,
                        B.lvl = 0.66,
                        add = "least impacted"
                )
        # ispf <-
        #         indicator_analysis(
        #                 data2 = puf2,
        #                 data3 = puf3,
        #                 B.lvl = 0.66,
        #                 add = "purified"
        #         )

        saveRDS(
                object = list(isaf = isaf,
                              islf = islf),
                file = paste0("auxilliary/indi_typ_", data.set, ".rds")
        )
} else if (options$typical) {
        typical.list <- readRDS(file = paste0("auxilliary/indi_typ_", data.set, ".rds"))
        for (i in seq_along(typical.list)) {
                assign(x     = names(typical.list)[i],
                       value = typical.list[[i]])
        }
}

jac.fam <- rbindlist(list(jaccard_extract(isaf),jaccard_extract(islf)))
mid.fam <- rbindlist(list(mid_extract(isaf),mid_extract(islf)))
```


```{r PLOT TYPICAL TAXA}
jaccard_plot(jac.fam, "family")
mid_plot(mid.fam, "family")
```

```{r create summary table}
summary.out <- rbindlist(
        list(
        
                an_family_mean,
                
                an_family_mean,
                
                ivs_family_mean,
                
                ivs_family_mean,
         
                cs_family_mean,
       
                cs_family_mean
        )
)
fwrite(summary.out, file = paste0(data.set,".csv"))
```

