---
title: 'Individual Data Set: Monitoring Spain'
author: "Jonathan Jupke"
output: html_document
---

```{r SETUP, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning=FALSE)
pacman::p_load(
        ade4,
        cluster,
        corrplot,
        data.table,
        dplyr,
        ggplot2,
        fs,
        indicspecies,
        lubridate,
        magrittr,
        mapview,
        sf,
        stringr,
        tidyr,
        tmap,
        vegan
)
source("../helper_functions.R")
tmap_mode("view")
```

```{r CREATE OPTIONS}
#- What to load and what to compute
#- TRUE means load
options <- list(
  pre =      FALSE,
  distance = FALSE,
  mantel   = FALSE
)
```

```{r CREATE GLOBAL VARIABLES 1}
data.set = "monitoring_spain"
all_seasons <- c("spring", "summer", "autumn", "winter")
seasons <- 1:3
```


```{r CREATE DA, LI and PU}
most.recent.data <- 
        fs::dir_ls("../../data/combined_data/", regexp = "_core_taxa_data.rds") |> 
        stringr::str_remove("../../data/combined_data/03_") |> 
        stringr::str_remove("_core_taxa_data.rds") |> 
        lubridate::ymd() |> 
        {\(x) x[which.max(x)]}()

data <-
  readRDS(file = paste0(
    "../../data/combined_data/03_",
    most.recent.data,
    "_core_taxa_data.rds"))
```


```{r CREATE DA, LI and PU}

da <-
        lapply(data, function(x)
                x[data.set == "Monitoring data from Spain"])
lapply(da, nrow)
#- create subset of least impacted sites
li <-
        lapply(seasons, function(x)
                da[[x]][fec.least.impacted == TRUE])
lapply(li, nrow)
#- create subset of sites that are least impacted and removed from regional borders
pu <-
        lapply(seasons, function(x)
          li[[x]][illies_distance >= 25000 & bgr_distance >= 25000])
```

```{r PLOT MAPS}
map <- 
  rbindlist(li) |> 
  unique(by = "gr_sample_id") |> 
  st_as_sf()
tm_shape(map) + tm_dots() + tm_facets(by = "season")
```

```{r CHECK TYPOLOGIES, results = "hide"}
#- check how many instances of each type are there

map |> filter(season == "spring") |> pull(bgr) |> table()
map |> filter(season == "summer") |> pull(bgr) |> table()
map |> filter(season == "autumn") |> pull(bgr) |> table()
map |> filter(season == "spring") |> pull(illies) |> table()
map |> filter(season == "summer") |> pull(illies) |> table()
map |> filter(season == "autumn") |> pull(illies) |> table()
map |> filter(season == "spring") |> pull(brt12) |> table()
map |> filter(season == "summer") |> pull(brt12) |> table()
map |> filter(season == "autumn") |> pull(brt12) |> table()


nrow(da[[3]][is.na(species)])/nrow(da[[3]])
nrow(da[[3]][is.na(genus)])/nrow(da[[3]])
nrow(da[[3]][is.na(family)])/nrow(da[[3]])
```

```{r GLOBAL VARIBLES 2}
seasons <- 1:3
typologies <- c("brt12", "brt12_bgr", "bgr")
```

```{r RUN PRE2 AND 3}
if (!options$pre){ 

        daf2 <- prep1(data = da,
                      taxon = "family")
        lif2 <- prep1(data = li,
                      taxon = "family")
        puf2 <- prep1(data = pu,
                      taxon = "family")
        lif2.abu <- prep1(data = li, taxon = "family", abundance.to.pa = FALSE)
        

  daf3 <- prep2(daf2)
  lif3 <- prep2(lif2)
  puf3 <- prep2(puf2)
  lif3.abu <- prep2(lif2.abu) 
  
  saveRDS(
          object = list(
                  daf2 = daf2,
                  lif2 = lif2,
                  puf2 = puf2,
                  daf3 = daf3,
                  lif3 = lif3,
                  puf3 = puf3,
                  lif3.abu = lif3.abu
          ),
          
    file = paste0("auxilliary/pre_",data.set,".rds")
  )
} else if (options$pre){
  pre = readRDS(file = paste0("auxilliary/pre_",data.set,".rds"))
  for (i in seq_along(pre)){
    assign(x     = names(pre)[i], 
           value = pre[[i]])
  }
}
```

```{r COMPUTE DISTANCE MATRICES}
# DISTANCE MATRIX  ------------------------------------------------------------------
if (!options$distance) {

  daf.dist <- daf3 |> prep3()
  lif.dist <- lif3 |> prep3()
  puf.dist <- puf3 |> prep3()
  lif.abu.dist <- lif3.abu |> prep3()

  saveRDS(
          object = list(

                  daf.dist = daf.dist,
                  lif.dist = lif.dist,
                  puf.dist = puf.dist,
                  lif.abu.dist = lif.abu.dist 
          ),
          file = paste0("auxilliary/distance_", data.set, ".rds")
  )
} else if (options$distance) {
  distance_list = readRDS(file = paste0("auxilliary/distance_", data.set, ".rds"))
  for (i in seq_along(distance_list)) {
    assign(x     = names(distance_list)[i],
           value = distance_list[[i]])
  }
}
```

```{r COMPUTE MANTEL TEST}
  #- family (ABU) to family (PA)
  m15 <- lapply(seasons, function(x) mantel.rtest(lif.abu.dist[[x]], lif.dist[[x]]))

```