---
title: 'Individual data sets: RCS'
author: "Jonathan Jupke"
output: html_document
---

```{r SETUP, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning=FALSE)
pacman::p_load(
        ade4,
        cluster,
        data.table,
        dplyr,
        ggplot2,
        indicspecies,
        magrittr,
        mapview,
        sf,
        tidyr,
        tmap,
        vegan
)
source("../helper_functions.R")
tmap_mode("view")
```

```{r CREATE OPTIONS}
#- What to load and what to compute
#- TRUE means load
options <- list(
  pre =      TRUE,
  distance = TRUE,
  anosim =   TRUE,
  typical =  TRUE
)
```


```{r CREATE GLOBAL VARIABLES 1}
data.set = "RCS"
all_seasons <- c("spring", "summer", "autumn", "winter")
seasons <- 1:3
```


```{r CREATE DA, LI and PU}

most.recent.data <- 
        fs::dir_ls("../../data/combined_data/", regexp = "_core_taxa_data.rds") |> 
        stringr::str_remove("../../data/combined_data/03_") |> 
        stringr::str_remove("_core_taxa_data.rds") |> 
        lubridate::ymd() |> 
        {\(x) x[which.max(x)]}()

data <-
        readRDS(file = paste0("../../data/combined_data/03_", most.recent.data,"_core_taxa_data.rds"))
da <-
        lapply(data, function(x)
                x[data.set == "Monitoring data from the RCS national network"])
lapply(da, nrow)
da <-
        lapply(da, function(x)
                x[!is.na(her)])
#- create subset of least impacted sites
li <-
        lapply(seasons, function(x)
                da[[x]][fec.least.impacted == TRUE])
#- create subset of sites that are least impacted and removed from regional borders
pu <-
        lapply(seasons, function(x)
                li[[x]][illies_distance >= 25000 & bgr_distance >= 25000])
```


```{r PLOT MAPS }
map <- 
  rbindlist(li) |> 
  unique(by = "gr_sample_id") |> 
  st_as_sf()
tm_shape(map) + tm_dots(col = "brt12") + tm_facets(by = "season")
```


```{r CHECK TYPOLOGIES, results = 'hide'}
#- check how many instances of each type are there
map |> filter(season == "spring") |> pull(bgr) |> table()
map |> filter(season == "summer") |> pull(bgr) |> table()
map |> filter(season == "autumn") |> pull(bgr) |> table()
#- bgr can be used in each season

map |> filter(season == "spring") |> pull(illies) |> table()
map |> filter(season == "summer") |> pull(illies) |> table()
map |> filter(season == "autumn") |> pull(illies) |> table()
#- illies can be used in each season 

map |> filter(season == "spring") |> pull(brt12) |> table()
map |> filter(season == "summer") |> pull(brt12) |> table()
map |> filter(season == "autumn") |> pull(brt12) |> table()
#- brt can be used in each season

map |> filter(season == "spring") |> pull(her) |> table()
map |> filter(season == "summer") |> pull(her) |> table()
map |> filter(season == "autumn") |> pull(her) |> table()
#- her has many rare regions. Summer looks best 

c(nrow(da[[1]][is.na(species)])/nrow(da[[1]]), nrow(da[[2]][is.na(species)])/nrow(da[[2]]), nrow(da[[3]][is.na(species)])/nrow(da[[3]]))
c(nrow(da[[1]][is.na(genus)])  /nrow(da[[1]]), nrow(da[[2]][is.na(genus)])  /nrow(da[[2]]), nrow(da[[3]][is.na(genus)])  /nrow(da[[3]]))
c(nrow(da[[1]][is.na(family)]) /nrow(da[[1]]), nrow(da[[2]][is.na(family)]) /nrow(da[[2]]), nrow(da[[3]][is.na(family)]) /nrow(da[[3]]))

#- species are missing from ~ 90% of observations 
#- genera are missing from ~ 13% of observations 
#- family are missing from no observation
```

```{r GLOBAL VARIBLES 2}
typologies <- c("brt12", "illies", "brt12_illies", "her", "brt12_bgr")
```


```{r RUN PRE2 AND 3}
if (!options$pre){ 
  dag2 <- prep1(data = da,
                taxon = "genus")
  daf2 <- prep1(data = da,
                taxon = "family")
  lig2 <- prep1(data = li,
                taxon = "genus")
  lif2 <- prep1(data = li,
                taxon = "family")
  pug2 <- prep1(data = pu,
                taxon = "genus")
  puf2 <- prep1(data = pu,
                taxon = "family")

  dag3 <- prep2(dag2)
  lig3 <- prep2(lig2)
  pug3 <- prep2(pug2)
  daf3 <- prep2(daf2)
  lif3 <- prep2(lif2)
  puf3 <- prep2(puf2)
  
  saveRDS(
    object = list(dag2 = dag2,
                  lig2 = lig2, 
                  pug2 = pug2,
                  dag3 = dag3,
                  lig3 = lig3,
                  pug3 = pug3,
                  daf2 = daf2,
                  lif2 = lif2, 
                  puf2 = puf2,
                  daf3 = daf3,
                  lif3 = lif3,
                  puf3 = puf3
                  ), 
    file = paste0("auxilliary/pre_",data.set,".rds")
  )
} else if (options$pre){
  pre = readRDS(file = paste0("auxilliary/pre_",data.set,".rds"))
  for (i in seq_along(pre)){
    assign(x     = names(pre)[i], 
           value = pre[[i]])
  }
}
```

```{r COMPUTE DISTANCE MATRICES}
# DISTANCE MATRIX  ------------------------------------------------------------------
if (!options$distance) {
  dag.dist <- dag3 |> prep3()
  lig.dist <- lig3 |> prep3()
  pug.dist <- pug3 |> prep3()
  daf.dist <- daf3 |> prep3()
  lif.dist <- lif3 |> prep3()
  puf.dist <- puf3 |> prep3()


  saveRDS(
          object = list(
                  dag.dist = dag.dist,
                  lig.dist = lig.dist,
                  pug.dist = pug.dist,
                  daf.dist = daf.dist,
                  lif.dist = lif.dist,
                  puf.dist = puf.dist
          ),
          file = paste0("auxilliary/distance_", data.set, ".rds")
  )
} else if (options$distance) {
  distance_list = readRDS(file = paste0("auxilliary/distance_", data.set, ".rds"))
  for (i in seq_along(distance_list)) {
    assign(x     = names(distance_list)[i],
           value = distance_list[[i]])
  }
}
```


# Mantel 
```{r MANTEL TEST}

  #- genus (PA) to family (PA)
  m1 <- lapply(1:3, function(x) mantel.rtest(lig.dist[[x]], lif.dist[[x]]))

m1 %<>% sapply(function(x) round(x$obs,3))
m1
```



# Point biserial Correlation through indicspecies 

```{r PBC}
ivsag  <- ivs(data2 = dag2, data3 = dag3, season.data = 1:3, typologies = typologies, add = "all observations")
ivslg  <- ivs(data2 = lig2, data3 = lig3, season.data = 1:3, typologies = typologies, add = "least impacted")
ivspg  <- ivs(data2 = pug2, data3 = pug3, season.data = 1:3, typologies = typologies, add = "purified")
ivsaf <- ivs(data2 = daf2, data3 = daf3, season.data = 1:3, typologies = typologies, add = "all observations")
ivslf <- ivs(data2 = lif2, data3 = lif3, season.data = 1:3, typologies = typologies, add = "least impacted")
ivspf <- ivs(data2 = puf2, data3 = puf3, season.data = 1:3, typologies = typologies, add = "purified")

ivs_genus   <- rbindlist(list(ivsag, ivslg, ivspg))
ivs_family  <- rbindlist(list(ivsaf, ivslf, ivspf))

ivs_genus_mean  <- ivs_genus[,mean(indval), by = c("typology", "type")]
ivs_genus_mean[,c("taxon.level", "variable") := .("genus" , "ivs_corr")]
ivs_family_mean  <- ivs_family[,mean(indval), by = c("typology", "type")]
ivs_family_mean[,c("taxon.level", "variable") := .("family" , "ivs_corr")]
```

```{r PLOT PBC}
ivs.plot1(ivs_genus, taxon = "genus")
ivs.plot1(ivs_family, taxon = "family")
```

```{r COMPUTE CLASSIFICATION STRENGTH}
csag <- class.strength(data2 = dag2, data4 = dag.dist, season.data = 1:3, add = "all observations")
cslg <- class.strength(data2 = lig2, data4 = lig.dist, season.data = 1:3, add = "least impacted")
cspg <- class.strength(data2 = pug2, data4 = pug.dist, season.data = 1:3, add = "purified")
csaf <- class.strength(data2 = daf2, data4 = daf.dist, season.data = 1:3, add = "all observations")
cslf <- class.strength(data2 = lif2, data4 = lif.dist, season.data = 1:3, add = "least impacted")
cspf <- class.strength(data2 = puf2, data4 = puf.dist, season.data = 1:3, add = "purified")

saveRDS(
  object = list(
    csag = csag,
    cslg = cslg,
    cspg = cspg,
    csaf = csaf,
    cslf = cslf,
    cspf = cspf
  ),
  file = paste0("auxilliary/cs_",data.set,".rds")
)

cs_genus   <- rbindlist(list(csag, cslg, cspg))
cs_family  <- rbindlist(list(csaf, cslf, cspf))

cs_genus_mean  <- cs_genus[,mean(cs), by = c("typology", "type")]
cs_genus_mean[,c("taxon.level", "variable") := .("genus" , "cs")]
cs_family_mean  <- cs_family[,mean(cs), by = c("typology", "type")]
cs_family_mean[,c("taxon.level", "variable") := .("family" , "cs")]

```

```{r PLOT CLASSIFICATION STRENGTH}
class.strength.plot1(cs_family, taxon = "genus")
class.strength.plot2(cs_family, taxon = "genus")
class.strength.plot3(cs_family, taxon = "genus")
class.strength.plot1(cs_family, taxon = "family")
class.strength.plot2(cs_family, taxon = "family")
class.strength.plot3(cs_family, taxon = "family")
```

# Silhouette Width 

```{r COMPUTE SILHOUETTES}
siag      <- wraper_silhouette(data2 = dag2, distance = dag.dist, add = "all observations")
silg      <- wraper_silhouette(data2 = lig2, distance = lig.dist, add = "least impacted")
sipg      <- wraper_silhouette(data2 = pug2, distance = pug.dist, add = "purified")
si_genus  <- rbindlist(list(siag, silg, sipg))
siaf      <- wraper_silhouette(data2 = daf2, distance = daf.dist, add = "all observations")
silf      <- wraper_silhouette(data2 = lif2, distance = lif.dist, add = "least impacted")
sipf      <- wraper_silhouette(data2 = puf2, distance = puf.dist, add = "purified")
si_family <- rbindlist(list(siaf, silf, sipf))
```


```{r PLOT SILHOUETTES}
silhouette.plot1(x = si_genus, taxon = "genus")
silhouette.plot1(x = si_family, taxon = "family")
```

# ANOSIM 
```{r COMPUTE ANOSIM}
if (!options$anosim) {
        anag <-
                wraper_anosim(
                        grouping = dag2,
                        distance = dag.dist,
                        permutations = 99,
                        add = "all observations"
                )
        anlg <-
                wraper_anosim(
                        grouping = lig2,
                        distance = lig.dist,
                        permutations = 99,
                        add = "least impacted"
                )
        anpg <-
                wraper_anosim(
                        grouping = pug2,
                        distance = pug.dist,
                        permutations = 99,
                        add = "purified"
                )
        
        anaf <-
                wraper_anosim(
                        grouping = daf2,
                        distance = daf.dist,
                        permutations = 99,
                        add = "all observations"
                )
        anlf <-
                wraper_anosim(
                        grouping = lif2,
                        distance = lif.dist,
                        permutations = 99,
                        add = "least impacted"
                )
        anpf <-
                wraper_anosim(
                        grouping = puf2,
                        distance = puf.dist,
                        permutations = 99,
                        add = "purified"
                )
        
        saveRDS(
                object = list(
                        anag = anag,
                        anlg = anlg,
                        anpg = anpg,
                        anaf = anaf,
                        anlf = anlf,
                        anpf = anpf
                ),
                file = paste0("auxilliary/anosim_", data.set, ".rds")
        )
} else if (options$anosim) {
        anosim.list = readRDS(file = paste0("auxilliary/anosim_", data.set, ".rds"))
        for (i in seq_along(anosim.list)) {
                assign(x     = names(anosim.list)[i],
                       value = anosim.list[[i]])
        }
}



an_genus  <- rbindlist(list(anag, anlg, anpg))
an_genus_mean  <- an_genus[, mean(R), by = c("typology", "type")]
an_genus_mean[, c("taxon.level", "variable") := .("genus" , "Anosim R")]
an_family  <- rbindlist(list(anaf, anlf, anpf))
an_family_mean  <- an_family[, mean(R), by = c("typology", "type")]
an_family_mean[, c("taxon.level", "variable") := .("family" , "Anosim R")]
```


```{r PLOT ANOSIM}
anosim.plot1(x = an_genus, taxon = "genus")
anosim.plot1(x = an_family, taxon = "family")
```

# Indicator and Typical taxa
```{r analysis TYPICAL TAXA}
if (!options$typical){
        isag <-
                indicator_analysis(
                        data2 = dag2,
                        data3 = dag3,
                        B.lvl = 0.50,
                        add = "all observations"
                )
        islg <-
                indicator_analysis(
                        data2 = lig2,
                        data3 = lig3,
                        B.lvl = 0.50,
                        add = "least impacted"
                )
        ispg <-
                indicator_analysis(
                        data2 = pug2,
                        data3 = pug3,
                        B.lvl = 0.50,
                        add = "purified"
                )
        isaf <-
                indicator_analysis(
                        data2 = daf2,
                        data3 = daf3,
                        B.lvl = 0.66,
                        add = "all observations"
                )
        islf <-
                indicator_analysis(
                        data2 = lif2,
                        data3 = lif3,
                        B.lvl = 0.66,
                        add = "least impacted"
                )
        ispf <-
                indicator_analysis(
                        data2 = puf2,
                        data3 = puf3,
                        B.lvl = 0.66,
                        add = "purified"
                )

        saveRDS(
                object = list(isaf = isaf,
                              islf = islf,
                              ispf = ispf,
                              isag = isag,
                              islg = islg,
                              ispg = ispg),
                file = paste0("auxilliary/indi_typ_", data.set, ".rds")
        )
} else if (options$typical) {
        typical.list <- readRDS(file = paste0("auxilliary/indi_typ_", data.set, ".rds"))
        for (i in seq_along(typical.list)) {
                assign(x     = names(typical.list)[i],
                       value = typical.list[[i]])
        }
}

jac.fam <- rbindlist(list(jaccard_extract(isaf),jaccard_extract(islf),jaccard_extract(ispf)))
mid.fam <- rbindlist(list(mid_extract(isaf),mid_extract(islf),mid_extract(ispf)))
```


```{r PLOT TYPICAL TAXA}
jaccard_plot(jac.fam, "family")
mid_plot(mid.fam, "family")
```

```{r create summary table}
summary.out <- rbindlist(
        list(
        
                an_genus_mean,
                ivs_genus_mean,
                ivs_genus_mean,
                cs_genus_mean,
                cs_genus_mean,
                an_family_mean,
                ivs_family_mean,
                ivs_family_mean,
                cs_family_mean,
                cs_family_mean
        )
)
fwrite(summary.out, file = paste0(data.set,".csv"))
```