---
title: "WISER"
author: "Jonathan Jupke"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
pacman::p_load(
        ade4,
        cluster,
        data.table,
        dplyr,
        fs,
        ggplot2,
        indicspecies,
        lubridate,
        magrittr,
        mapview,
        sf,
        stringr,
        tidyr,
        tmap,
        vegan
)
source("../helper_functions.R")
tmap_mode("view")
```

```{r set options}
#- What to load and what to compute
#- TRUE means load
options <- list(
  pre =      TRUE,
  distance = TRUE
)
```

```{r create global variables 1}
data.set = "wiser"
all_seasons <- c("spring", "summer", "autumn", "winter")
seasons <- 1:3
```

```{r READ DATA}
most.recent.data <-
  dir_ls("../../data/combined_data/", regexp = "_core_taxa_data.rds") |>
  str_remove("../../data/combined_data/03_") |>
  str_remove("_core_taxa_data.rds") |>
  ymd() |>
  {\(x) x[which.max(x)]}()


data <-
        readRDS(
                file = 
                        paste0(
                                "../../data/combined_data/03_",
                                most.recent.data,
                                "_core_taxa_data.rds"
                                )
                )
```

```{r}
da <-
  lapply(data, function(x)
    x[data.set == "WISER"])
#- create subset of least impacted sites
li <-
  lapply(seasons, function(x)
    da[[x]][fec.least.impacted == TRUE])
#- create subset of sites that are least impacted and removed from regional borders
pu <-
  lapply(seasons, function(x)
    li[[x]][illies_distance >= 25000 & bgr_distance >= 25000])
```

```{r MAP}
map <- 
  rbindlist(li) |> 
  unique(by = "gr_sample_id") |> 
  st_as_sf()
tm_shape(map) + tm_dots() + tm_facets(by = "season")
```


Genus and family can be analyzed. Species level information is missing from to many observations. 
```{r}

map |> filter(season == "spring") |> pull(bgr)    |> table()
map |> filter(season == "spring") |> pull(illies) |> table()
map |> filter(season == "spring") |> pull(brt12)  |> table()

map |> filter(season == "summer") |> pull(bgr)    |> table()
map |> filter(season == "summer") |> pull(illies) |> table()
map |> filter(season == "summer") |> pull(brt12)  |> table()

map |> filter(season == "autumn") |> pull(bgr)    |> table()
map |> filter(season == "autumn") |> pull(illies) |> table()
map |> filter(season == "autumn") |> pull(brt12)  |> table()

typologies <- c("brt12", "illies", "bgr")

c(nrow(da[[1]][is.na(species)])/nrow(da[[1]]), nrow(da[[2]][is.na(species)])/nrow(da[[2]]), nrow(da[[3]][is.na(species)])/nrow(da[[3]]))
c(nrow(da[[1]][is.na(genus)])  /nrow(da[[1]]), nrow(da[[2]][is.na(genus)])  /nrow(da[[2]]), nrow(da[[3]][is.na(genus)])  /nrow(da[[3]]))
c(nrow(da[[1]][is.na(family)]) /nrow(da[[1]]), nrow(da[[2]][is.na(family)]) /nrow(da[[2]]), nrow(da[[3]][is.na(family)]) /nrow(da[[3]]))
```

```{r pre}
if (!options$pre) {
  seasons = 1:3
  dag2 <- prep1(data = da,
                taxon = "genus")
  daf2 <- prep1(data = da,
                taxon = "family")
  lig2 <- prep1(data = li,
                taxon = "genus")
  lif2 <- prep1(data = li,
                taxon = "family")
  pug2 <- prep1(data = pu,
                taxon = "genus")
  puf2 <- prep1(data = pu,
                taxon = "family")
  lig2.abu <-
    prep1(data = li,
          taxon = "genus",
          abundance.to.pa = FALSE)
  lif2.abu <-
    prep1(data = li,
          taxon = "family",
          abundance.to.pa = FALSE)
  dag3 <- prep2(dag2)
  lig3 <- prep2(lig2)
  pug3 <- prep2(pug2)
  daf3 <- prep2(daf2)
  lif3 <- prep2(lif2)
  puf3 <- prep2(puf2)
  lig3.abu <- prep2(lig2.abu) 
  lif3.abu <- prep2(lif2.abu) 
  
  saveRDS(
    object = list(
      dag2 = dag2,
      lig2 = lig2,
      pug2 = pug2,
      dag3 = dag3,
      lig3 = lig3,
      pug3 = pug3,
      daf2 = daf2,
      lif2 = lif2,
      puf2 = puf2,
      daf3 = daf3,
      lif3 = lif3,
      puf3 = puf3, 
      lig3.abu = lig3.abu, 
      lif3.abu = lif3.abu 
    ),
    file = paste0("auxilliary/pre_", data.set, ".rds")
  )
} else if (options$pre) {
  pre = readRDS(file = paste0("auxilliary/pre_", data.set, ".rds"))
  for (i in seq_along(pre)) {
    assign(x     = names(pre)[i],
           value = pre[[i]])
  }
}
```

```{r distance_matrices}
# DISTANCE MATRIX  ------------------------------------------------------------------
if (!options$distance) {
  dag.dist <- dag3 |> prep3()
  lig.dist <- lig3 |> prep3()
  pug.dist <- pug3 |> prep3()
  daf.dist <- daf3 |> prep3()
  lif.dist <- lif3 |> prep3()
  puf.dist <- puf3 |> prep3()
  lig.abu.dist <- lig3.abu |> prep3()
  lif.abu.dist <- lif3.abu |> prep3()

  saveRDS(
    object = list(
        dag.dist = dag.dist,
        lig.dist = lig.dist,
        pug.dist = pug.dist,  
      daf.dist = daf.dist,
      lif.dist = lif.dist,
      puf.dist = puf.dist,
      lig.abu.dist = lig.abu.dist, 
      lif.abu.dist = lif.abu.dist
    ),
    file = paste0("auxilliary/distance_", data.set, ".rds")
  )
} else if (options$distance) {
  distance_list = readRDS(file = paste0("auxilliary/distance_", data.set, ".rds"))
  for (i in seq_along(distance_list)) {
    assign(x     = names(distance_list)[i],
           value = distance_list[[i]])
  }
}
```

```{r Compute Mantel test}
 
if (!options$mantel){
  #- genus (ABU) to genus (PA)
  m10 <- lapply(1:3, function(x) mantel.rtest(lig.abu.dist[[x]], lig.dist[[x]]))
  #- family (ABU) to family (PA)
  m15 <- lapply(1:3, function(x) mantel.rtest(lif.abu.dist[[x]], lif.dist[[x]]))

  saveRDS(list(
    m10 = m10,
    m15 = m15
    ), 
    file = paste0("auxilliary/mantel_", data.set, ".rds"))
  
} else {
  mantel.list = readRDS(file = paste0("auxilliary/mantel_", data.set, ".rds"))
  for (i in seq_along(mantel.list)) {
    assign(x     = names(mantel.list)[i],
           value = mantel.list[[i]])
  }
}  
```

```{r}
m10 |> sapply(function(x) x$obs)
m15 |> sapply(function(x) x$obs)
```

