# Abstract 



<!-- 
###  ——————————————————  ###
###  ——— GUIDELINES ———  ###
###  ——————————————————  ###
        
—————— Saramäki ——————  
- SETUP 
-> CONFRONTATION 
-> RESOLUTION 
-> EPILOGUE 
————————————————————————

—————— STOTEN ——————
The purpose of the research, the principal results and major conclusions.
300 words 
————————————————————————

--> 

<!-- TODO 
- add question hypothesis to abstract (PB) 

--> 


<!-- SETUP --> 
Human actions alter the composition and functioning of ecological communities on a global scale. 
These changes are especially rapid and intensive in freshwater ecosystems. 
Comprehensive and international regulatory frameworks are necessary to slow down, halt and reverse the ongoing loss of freshwater biodiversity. 
These regulatory frameworks, such as the Water Framework Directive (WFD), typically simplify freshwater ecosystems through classification systems that use selected features to derive a typology. 
Broad river types are a recently proposed pan-European typology for lotic freshwater systems.
They unify the assortment of existing national typologies and are quickly gaining traction within the research community. 
However, it remains to be seen whether this environmental typology effectively delineates ecological communities. 
Such biological validation is critical to establish the typologies suitability for quality assessments based on biological quality elements.  
<!-- CONFRONTATION --> 
In this paper, we test whether the broad river types summarize variation between macroinvertebrate communities effectively and whether combing it with ecoregions can improve them.  
Moreover, we derived lists of taxa that typically occur within the types of each typology and evaluated their taxonomic similarities.
<!-- RESOLUTION --> 
<!-- Even tough performance differed between validity metrics, the BRT typology rarely ranked among the best. -->
<!-- This was confirmed by our finding that macroinvertebrate assemblages of different BRT-types were more similar to each other than in the other typologies.  -->
<!-- Overall, regional typologies achieved higher validity scores than those based on reaches. -->
<!-- However, no typology achieved high cluster validity scores. -->
<!-- EPILOGIE -->
<!-- Our findings show that the BRT typology predicts invertebrate community composition worse than previously established typologies.  -->
<!-- However, none of the typologies considered was a good descriptor of invertebrate biogeography.  -->
<!-- Further improvement of freshwater typologies has the potential to benefit macroecological research, improve biomonitoring and render conservation efforts more effective.  -->
<!-- 

##### ----- OLD DRAFTS ----- ##### 

To reduce the impact of known stressors and prevent the emergence of new ones, comprehensive international regulatory frameworks are necessary. 
The Water Framework Directive (WFD) aims to achieve this for the European Union.
Despite missing its initial target of elevating all waterbodies to good quality in 2015, it has let to considerable progress in our knowledge of European waterbodies as well as new and improved methods for biomonitoring.
Central to the WFD the division of freshwater systems into types, each with different reference conditions. 
While national states use national typologies for their evaluations, a Pan-European typology of rivers has recently been proposed. 
Here we evaluate whether this typology is a good classifications of aquatic macroinvertebrate communities, compare it with other freshwater typologies, and derive typical and indicator taxa for its types.
To this end, we 
All our analyses indicate, that macroinvertebrate differ between some of the proposed types but large redundancies reamin. 


--> 


