# Discussion 

We compared the partitioning of aquatic invertebrate samples based five different freshwater typologies. 
Three were stream-based (BRT12 and 20 as well as GloRic) and two were ecoregion-based (Illies and EEA). 
To evaluate the cluster validity metrics we used for the comparison, we also computed a biological clustering of the samples and 100 random partitions of the data.
We expected the values of the cluster validity metrics for the five freshwater typologies to lie in the interval between random partitioning and biological classification. 
This expectation was met, with the exception the silhouette widths (refer to figure).

<!-- Summary of clusters --> 
Overall, the freshwater ecoregions proposed by @illies1978limnofauna performed best in our assessment followed by the bio-geographical regions, broad river types 12, broad river types 20 and GloRiC.
Illies freshwater ecoregions had the highest (when disregarding the biological classification) IndVal statistic and classification strength.
While in BRT12 is a close second in the IndVal statistic, the CS is markedly higher for Illies freshwater ecoregions than any of the other typologies. 
The higher score for the EEA bio-geographical regions in CH can be explained be the lower number of groups which increases the second term in equation xxxxxx. 

Average silhouette widths were relatively low for all groups. 
Only ecoregion-based typologies received positive scores for the ordinary silhouette width at $p=1$. 
However, the $ASW_{\infty}$, was highest for BRT12 but still below zero. 
The low ASWs indicate that most observations could also be regarded as an instance of a different type, without loosing much (or, in the case of negative ASWs, any) discriminatory power. 
$ASW_{-\infty}$ gives the largest weight to the separation of clusters without considering compactness. 
It clearly shows a stronger separation between the types of ecoregion-based typologies than between those of reach-based ones.
It is also at this level that all typologies have positive ASWs and that the difference to random partitions is largest. 
The difference between regions and reaches and between typologies and null-partitions decreases with increasing $p$.
The negative $ASW_{\infty}$ indicate that for each of the typologies, there is some site within there own type that is more dissimilar to it, than the most dissimilar site from the next closest cluster. 

<!-- Regional outperform local --> 
Therefore, bio-region approaches that assign large contiguous areas to a single type, were a better summary of our large data set of invertebrate occurrences than reach-scale typologies.  
It is possible that the constrains of our study played in favor of regional approaches. 
The taxonomic resolution of our data only allowed inferences at the genus level.
Potentially, species level data would have highlighted larger differences at smaller scales and hence be better summarized by typologies with smaller mapping units.    
Along the same lines, @Moog2004 showed that higher taxonomic resolution was necessary to delineate smaller ecoregions and the same logic could expand to reach-scale typologies. 
Similarly, @Verdonschot2006 showed that differences in classification strength were noticeable between 'best-available' and family level data on a pan-European scale. 
However, the difference was not large and their analysis does not allow to infer the loss of using genus instead of species level data.
@Hawkins2000 notes that across taxa groups and typologies, higher taxonomic resolution does not always lead to greater classification strength.   
Additionally, the likelihood of assigning an observation to the wrong type due to inaccuracies in the spatial data are lower for ecoregions, where such mistakes can only happen toward the margins between types.
Especially very small rivers are largely missing from the river network representations used by GloRiC and BRT. 
New and finer data products [e.g. @Lin2021] might provide more accurate mapping of stream types.
Lastly, defining reference states is complicated, especially after the fact. 


However, the patterns we observed could also indicate either strong or weak dispersal limitation. 
The spatial distance between the instances of different types in reach-scale typologies is often small. 
Typically, landscapes and catchments are made up of mosaics of different stream types. 
In positing that assemblages vary between instances of different reach-scale types, we implicitly assume a that dispersal is strong enough for species to track variation in local conditions (L04), but not so strong that mass effect would overrule all environmentally induced patterns [@mouquet2003community].     
<!-- Instances of a type in reach-scale typologies can be far apart while ecoregions are compact and contiguous. -->
<!-- Dispersal limitation -->
<!-- Diving communities by stream-types therefore assumes that they are not strongly limited by dispersal which would make it impossible for individual of some species to reach isolated streams even though the site's environmental conditions would be favorable.  -->
If taxa are strongly limited by dispersal e.g. through historical and anthropogenic dispersal barriers [@leibold2010metacommunity;@Belletti2020] or thorugh sheer distance between sites, they are unable to reach potentially favorable sites.
In our case, stronger dispersal limitation would lead to larger differences between sites of the same type. 
Dispersal limitation leads to a pattern known as distance decay. 
Distance decay is often found at large spatial scales [@nekola1999distance, @morlon2008general] but varies in its magnitude between taxa, realms and degrees of latitude [@graco2021distance].
Studies have found  both, invertebrate communities that are predominantly structured by environment [e.g. @heino2012context; @landeiro2012roles] and those that are structured by space [@mykra2007scale;@astorga2012distance]. 
However, even for microbes, which under the Bass-Becking hypothesis ("everything is everywhere but the environment selects") were long considered to have cosmopolitan distributions, the role of dispersal limitation, at least at large spatial scale, is becoming evident [@Telford2006, @soininen2012macroecology, @lindstrom2012local].
Our analysis of generalized silhouette width showed that separation between assemblages of broad river types decreases if the weight of outliers (i.e. $p$) is increased up to a point where separation is lower than is seen in random partitions. 
This pattern could be explained by strong dispersal limitation leading to divergent communities in comparable environments. 
<!-- Mass Effect --> 
At the other extreme, dispersal is strong enough to to allow species to persist in habitats otherwise unsuitable for growth. 
The process is known as source-sink dynamics or mass-effects (sensu @wilson1984measuring). 
In our case, mass effects would lead to smaller differences between sites of different types. 
Such effects are expected to exist primarily on small spatial scales [@ng2009hierarchical]. 
What constitutes a small spatial scale depends on the dispersal ability of species [@Heino2015] but for many taxa the distance between reaches would fall under this category, while the distances between regions are only small  at their margins.
Experimental studies indicate that the immigration flows that are required to alter community composition are large [@lindstrom2011importance;@logue2010species;@adams2014metacommunity;@adams2014metacommunity], and under natural conditions mass effect might be reduced, as organisms bias their dispersal towards favorable environments [@resetarits2013patch, @haegeman2015graphical]. 
However, tools to identify the imprint of mass effects in large ecological data sets remain an area of active development [e.g. @Leboucher2020]. 

<!-- Small scale vs. regional --> 
The better performance of ecoregions than reach-scale typologies might also be taken to support the notion, that the composition of aquatic macroinvertebrate communities tracks change in large-scale rather than small-scale variables. 
Many studies have investigated this question before. 
Among them are studies which have studied the explanatory potential of ecoregions, which might be considered as categorical combinations of large scale environmental conditions like climate, geology and altitude. 
@Verdonschot2004 used the data compiled during the AQEM project to investigate potential drivers of macroinvertebrate community composition. 
they found that the distribution of macroinvertebrates follows @illies1978limnofauna freshwater ecoregions and that large scale variables like geology explain most of the variation. 
However, using an extended data set, that included data from both AQUEM and STAR, @Verdonschot2006b did not find ecoregions to be a strong predictor of invertebrate community composition. 
Similarly, ecoregions explained a negligible amount of variance in community composition in Swedish boreal streams [@Johnson2004].
The review of @Hawkins2000 finds that ecoregion-based approaches usually outperform catchment-scale classifications, however the classification strength was generally weak.
The classification strengths of the studies they considered lay between 0.07 and 0.16 which corresponds to the ones we found, which ranged from `r cs_gl` to `r cs_ill`. 
This general range of values (i.e. below 0.2) is often found by similar studies [e.g.  @Snelder2004, @Heino2006, @Mykra2009, @Vasconcelos2013]. 
The degree to which assemblages are regulated regionally or locally likely depends on the magnitude of dispersal [@ryabov2011graphical].  
Synthesis of these findings is impeded by the fact that many of the studies relied on combinations of variance partitioning and eigenfunction analyses that has been shown to be flawed [@gilbert2010partitioning; @smith2010variation; @tuomisto2012modelling].
An alternative method to evaluate the importance of dispersal processes for community assembly has recently been proposed [@Vilmi2020]. 
@Heino2015 concluded that dispersal limitation is important for studies that consider multiple drainage basins, like this one.  

<!-- also dont like  -->
<!-- @Lorenz2004 like  -->
<!-- More studies on local vs regional:  -->
<!-- pro regional Urban et al 2006, DD   Corkum, 1989; Richards, Johnson & Host, 1996; Roth, Allan & Erickson, 1996; Lammert & Allan, 1999(from Johnson 2007) -->
<!-- @Johnson2007 found a more nuanced pattern where the single most important factor large scale factors most important single but when grouped local more important  -->


<!-- Biotic interactions --> 
A typologies based on environmental variables cannot account for the effects of biotic interactions. 
While these received much attention in in the early days of macroecology [@diamond1975assembly;@connor1983interspecific] the focus shifted towards environmental filters [e.g. @whittaker1970communities, @pearson2003predicting] assuming that biotic interactions are only important at local scales. 
Recently however, their role for macroecology as been revisited [@Wisz2013].
Propelled by a series of new methods [e.g. @Popovic2019, @ovaskainen2020joint] several studies have recently investigated the impact of biotic interactions in larger biogeographical patterns. 
While some indicate, that the role of environmental conditions is more important than that of biotic interactions [@elo2021does], others suggest that biotic interactions modulate the response the abiotic enviornment [@Abrego2021]. 

<!--INDVAL-->
Potamon species in RT2 and 4 Ind: Acroloxus, Anisus, Viviparus 
Potamon species in RT1 Ind : Theodoxus 
alpine species : Rhabdiopteryx indicator for RT15 is adjusted to high altitude rivers (according to Lorenz et al 2004 )
also Rhithrogena for RT14/ 15 (through Rithrogena alpestris), Rhyacophila (through Rhyacophila torrentium and vulgaris) for all mid- and high altitude types except RT14. 
Summary Indval similarity 
Summary Indval Traits 
<!--TA-->

<!-- General patterns -->
Several taxa occurred throughout all or most typical assemblages. 
These tramp species (sensu @McGeoch2002) were: 
the mayfly *Baetis sp.* or *Baetis rhodani*, 
*Chironomidae*, 
the beatle *Elmis aenea* or *Elmis*,
the caddisfly *Serratella ignita* is part of four typical assemblages.  

<!-- Summary TA similarity -->

<!-- Notable TAs      --> 
<!-- TA1              -->
The typical assemblage of very large river (RT1) harbors many Pontocaspian species that are invasive in much of Europe like *Chelicorophium curvispinum*, *Dreissena polymorpha* and *Dikerogammarus villosus*.  
This all of them are specific to this river type, at 90% of their observations stem from this river type and they occur at least in 5% of the samples form this type. 
Part of our samples where taken in the native range of these species, however we also recorded occurrences in other very large rivers like ... .... . 
In addition to these Ponotcaspian taxa, *Potamogyrus* species are invasive from New Zealand. (REF) 
The presence of these taxa within the typical assemblage thus highlights large importance of neozoa as stressors in large rivers [@Leitner2020]. 
<!-- TA2              -->
The typical assemblage of lowland, siliceous rivers has has a high taxonomic resolution and consists mostly of Caddisfly species (6) and Coleoptera species (3) and includes several typical rhitron species such as *Esolus parallelepipedus*, *Elmis aenea* and *Hydropsyche pellucidula*. 
The invasive *Potamogyrus antipodanum* also occurs often in this river type. 
<!-- TA3              -->
The typical assemblage of small to small  lowland, siliceous rivers is very similar to that of large lowland siliceous rivers (refer to figure). 
Two species are specific to this river type, the snail *Physa fontinalis* and the leech *Piscicola geometra*. 
Additionally, Leuctra,  the only typical stonefly species from BRT2, is not typical for BRT3 but instead the black fly *Simulium ornatum*. 
<!-- TA4_5      -->
In the two combined lowland calcareous or mixed stream types the typical assemblage contains notably less caddisflies than in the former lowland types. 
Only *Serratella ignita* and *Caenis sp.* are typical for this type. 
Unique to this river type are the two parasitic species *Potamothrix hammoniensis* and *Glossiphonia complanata*. 
<!-- TA8_10_11_18 --> 
The large combined type of mid-altitude rivers BRT8_10_11_18 
Three different families of Dipterans are typical: Simulidae, Chironomidae and Limoniidae. 
In addition to the two genera of Coleoptera there were typical for lowland streams, a third genus, Riolus, is typical for the combined mid-altitude type. 
The genus is known to be common in calcareous mid-altitude streams [@berthelemy1966recherches;@hebauer1986kafer].          
<!-- TA9 --> 
The typical assemblage from small, siliceous mid-altitude rivers (BRT9) differs markedly from that of  the other mid-altitude streams. 
The Jaccard Similartiy is only 0.18. 
Partly, this is due to four specific species (the caddisflies *Agapetus ochripes*,  *Ithytrichia lamellaris*, *Potamophylax cingulatus*, and the mayfly *Heptagenia dalecarlica*) but also to the two genera of stoneflies that are only typical for this river type (Isoperla and Protonemura). 
<!-- TA14_15_16 --> 
Lastly, the typical assemblage of high-altitude rivers has the lowest taxonomic resolutions. 
Almost half of the typical taxa (6 out of 14) are at family level or above and no species are included. 
As in the combined type with mid-altitude streams, we find four families of dipterans as well as Oligochaetes in this assemblage. 
The dipteran families include all three typical of mid-altitude streams and Empididae.
The mayfly genus Rhithrogena is the only one that only occurs in this typical assemblage. 




<!-- Traits -->
<!-- Tendency towards more shredders in high smaller rivers.  -->
<!-- Matches the predictions of the river continuum concept [@Vannote1980]. -->
<!-- The latter has been ciritized for xxx but seems not to be a large problem.  -->
<!-- In both kind of assemblages we derived, very large rivers differed most markedly from the other river types.  -->
<!-- Trends that always hold -> filtering in RT1; voltinism in RT1 ; crawling dominant ; size RT1  -->
<!-- Longer generation times were clearly associated with high altitude streams (more semi and less mutlivoltinism) in the indicator assemblages but not in the typical assemblages.  -->
<!-- This runs counter to results of Finn and Poff (2005) Freshwater Biology -->
<!-- Intraspecific trait variability - (https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13568) -->


<!-- Ways forward -->

Streams too large? See small waterbodies are important paper by ... and add the new stream system by ...

Explicit mentioning of meta community processes in BA (weist schon welches paper)

The typology of the WFD must be optimized not only for macroinvertebrates but for all four biological elements (macroinvertebrates, diatoms, fish, macrophytes) [@Dodkins2005].
Thus these taxa should also be assessed to draw a final conlcusion. 

Furthermore it remains unclear whether current ecoregions or stream classes will change uniformly with future climate change or will con- and diverge. 
Environmental legislative frameworks must acknowledge that climate change will alter their subjects and adapt when necessary [@Arneth2020]. 