<!-- Structure of the discussion 

1. Overview results (What did we see compare results to other studies)
1.1 anosim [x] 
1.2 classification strength
1.3 indval 
1.4 typical (tdb)

2. within type similarity 
3. meta community stuff 
4. the effect of taxonomic resolution on our results 
5. future of biomonitoring and typologies 
5.x we need to continuously update typologies (climate change, global change)
5.x combine with regios 
5.x modern approaches 
5.x recognize intermittent rivers in all of europe 
5.x lake influences 
6.x next up: other bqe 
--> 

<!-- 1. Overview Results --> 
## Classification performances
All three freshwater typologies account for more variation in macroinvertebrate samples than random partitions of the data. 
With very few exceptions, communities are more similar within than between types. 
There were more indicator families, which also were more indicative in the mean than would be expected from randomly assigned sites. 
Lastly, typical communities were less similar than would be expected by chance, indicating a change in the most common families.
Thus, we can neither reject the hypothesis that macroinvertebrate communities are more similar within than among types (H1) nor the hypothesis that the typologies delineate distinct typical and indicator assemblages (H2). 
The within-type similarity was largest in Illies Freshwater Ecoregions according to ANOSIM and classification strength. 
They also delineated the least similar typical communities. 
Indicative families, on average, had the highest indicator values in the Biogeographic Regions, while the number of indicator families was largest in the broad river types. 
Therefore, we can reject the hypothesis that the broad river types are a better classification of macroinvertebrate samples than Illies Freshwater Ecoregions or the Biogeographic regions (H3). 
<!-- 1.1 ANOSIM--> 
While the ANOSIMs were statistically significant, their effect sizes were small. 
For the least impaired samples, the R statistic was between 0.08 and 0.29. 
According to Clark and Gorley (2001), one should interpret R values below 0.5 as barely separable.
In their study of freshwater typologies for Ireland, @Dodkins2005 found the WFD System A typology to have an R statistic of 0.145. 
@marchant2000assessment observed a higher value of 0.33 for Australian ecoregions and interpret this as a weak match between typology and biota.
They advise against inferring patterns in community composition from the ecoregions.
An evaluation of Greek freshwater typology similarly found an R-value of 0.38 and inferred that the communities were strongly overlapping [@Lazaridou2013]. 
Finally, in an evaluation of stream typologies for Spain, @sanchez2007concordance employed a seasonal stratification scheme similar to ours and found R values ranging from 0.19 to 0.31.
In contrast to the former studies, @sanchez2007concordance interpret their results as supporting the tested typology.  
The R values of Illies Freshwater Ecoregions fall within the range of these previous studies; the R values of the other two typologies are comparatively low. 
These low values are plausible given that the majority of the studies above considered smaller areas but used a similar number of types. 
It is remarkable that Illies Freshwater Ecoregions perform on par with the small-scale typologies.  
<!-- ralf hat empfohlen das hier zu streichen 
Nonetheless, we confer with the majority of authors cited here that the low R statistic is more telling than the statistical significance.
The low pseudo-*p*-value shows that random partitions of the data overlap more strongly than the types of the typologies, but the low R statistic shows that the latter overlap as well. 
Thus, solely based on the ANOSIM, we would advise against inferring communities from types in all three typologies. 
--> 
<!-- 1.3 IndVal --> 
The range of absolute values of indicator scores is similar to that in @sanchez2007concordance but values are lower than was observed in other studies of concordance between macroinvertebrates and river types [e.g. @Bonada_Rieradevall_Prat_Resh_2006; @Banks_Li_Herlihy_2007; @Heino2006].
As with the other methods, one should differentiate between statistical and practical significance. 
@Kubosova_Brabec_Jarkovsky_Syrovatka_2010 set an absolute threshold of Indval > 0.4 to determine strongly indicative taxa, without providing a rationale for the threshold. 
According to this criterion, most of the identified indicator families are not strongly indicative, as most mean values are below 0.4. 

<!-- 1.2 classification strength --> 
We observed classification strengths between 0.02 and 0.1 which also lies at the lower end  of previous studies [e.g. @Hawkins2000; @Snelder2004; @Heino2006; @Mykra2009; @Vasconcelos2013].
We need to caution against such direct comparisons, however because details on the computation (is the within-type similarity weighted by group size, how exactly is between type similarity computed) were commonly missing from the method descriptions and we can not evaluate how large their influence is.
Additionally, the absolute value of the classification strength depends on the chosen similarity metric.  
<!-- Within type similarity --> 
The between-type similarity was remarkably constant among typologies, ranging from 0.26 to 0.27 (Figure S4). 
This value indicates that two sites are likely to share a quarter of the families from the combined pool of families, while two thirds of the families are unique to one of the sites.
The within-type similarity is more pertinent to this discussion, as the reference-condition approach of the WFD only works if the within-type similarity is high. 
A high between-type similarity would not entail serious problems for the reference-condition approach, but only highlight inefficiencies due to redundant types. 
However if the within-type similarity would be low, it would not be reasonable to assume similar communities at least impaired conditions. 
Note that a higher taxonomic resolution (i.e. genus- or species-level data) could only reduce the similarities but not increase it, since members of the same family can be different from genera or species but the same species can not be part of multiple families. 
A higher resolution could increase overall classification strength by decreasing between-type similarity stronger than within-type similarity but neither of the components by themselves. 
Therefore the within-type similarities presented here represent an upper bound.
In the broad river types, the within-type similarities of least impaired samples ranged from 0.22 (RT1, autumn) to 0.45 (RT8, summer) (Figure S6).
The highest observed value implies that about half of the families from the shared pool occur at both sites, which in turn implies that, assuming both sites have the same species richness, about 75% of the families from a site also occur at the other site.
At the lower end of observed similarities, this falls to 33% of families. 
Across typologies, median values for within-type similarity can be approximated by one third (they range from 0.30 to 0.36).
For this similarity, assuming equal alpha diversity, 50% of families from each site are shared and 50% are unique.  

As a general trend, we observed that mid- and high-altitude river types (RT6-10) have higher within-type similarity than low-altitude river types (RT1-5, Figure S6). 
This idiosyncrasy  of mid- and high-altitude rivers was also observed by @Moog2004 and is in line with the identification of high-altitude areas as one of three large bioregions in Europe [@Verdonschot2006b]. 
The harshness of these environments (high seasonality, high flow velocity, steep slopes) can increase the importance of dispersal for community assembly [@Datry_2016] and thus decrease beta-diversity [@luBetaDiversityPatterns2019; @thompsonProcessBasedMetacommunity2020; but see @luComplexRelationshipsBeta2021].
With a mean within-type similarity of 0.24, which is lower than the mean between-type similarity, sites from very large rivers (RT1, Figure S6) were the most dissimilar. 
The communities of very large rivers (defined as having a catchment area above 10000 $km^2$) are strongly affected by multiple interacting stressors including alien species [@arbaciauskasAssessmentBiocontaminationBenthic2008], alteration of riparian vegetation [@leitnerMultipleStressorEffects2021] and navigation [@liebmann1967eingriffe; @gabelDifferentialEffectWave2011]. 
The magnitude of these stressors differs markedly between regions [@leitnerMultipleStressorEffects2021] and can override regional differences leading to less indicative communities [@fittkau1983versuch]. 
@borgwardt2019ex showed that this river type can be divided into seven types that can be clearly differentiated based on environmental and biological factors. 

## The Ecology of Typologies 

In positing that assemblages vary between instances of different reach-scale types, we implicitly assume that dispersal is strong enough for species to track variation in local conditions [@leibold2004metacommunity] but not so strong that mass effects overrule environmentally induced patterns [@mouquet2003community].
If taxa are strongly limited by dispersal e.g. through historical and anthropogenic dispersal barriers [@leibold2010metacommunity;@Belletti2020] or through the sheer distance between sites, they are unable to reach potentially favorable sites.
The stronger the dispersal limitation the weaker the effect of the environment on community composition.
Environmentally similar types, as the broad river types, fail to describe the main patterns in variation when dispersal limitation is strong. 
Variation within types would be higher and variation between types lower, than in a scenario with less dispersal limitation. 
Dispersal limitation leads to a pattern known as distance decay, which is often found at large spatial scales [@nekola1999distance; @morlon2008general] but varies in its magnitude between taxa, realms and degrees of latitude [@graco2021distance].
Studies have found  both, invertebrate communities that are predominantly structured by environment [e.g. @heino2012context; @landeiro2012roles] and those that are structured by space [@mykra2007scale;@astorga2012distance]. 
However, even for microbes, which under the Bass-Becking hypothesis ("everything is everywhere but the environment selects") were long considered to have cosmopolitan distributions [e.g. @Finlay2002], the role of dispersal limitation, at least at large spatial scales, is becoming evident [@Telford2006; @soininen2012macroecology; @lindstrom2012local]. 
It is likely that most macroinvertebrate communities are partly structured by dispersal processes, which are not considered in typologies that ignore the spatial proximity between instances of a type (e.g. the braod river types)
Similar difficulties arise for capturing the effect of biotic interactions with environmental typologies.  
Biotic interactions such as competition, parasitism or facilitation co-determine the distribution of species [@garcia-gironBioticInteractionsHold2020]. 
In that regard, they received much attention in the early days of macroecology [e.g. @diamond1975assembly;@connor1983interspecific] but the focus shifted towards environmental filters [e.g. @whittaker1970communities; @pearson2003predicting].
Biotic interactions were thought to matter only at local scales, while autecological [@townsend1994species] and environmental characteristics [@Southwood_1977] determine distributions. 
Lately, their role for macroecology has been revisited [e.g. @Wisz2013] partly due to the realization that many studies can not properly differentiate between environmental filtering and biotic interactions [@Kraft2015].
Propelled by a series of methodological advances [e.g. @popovic2019untangling; @ovaskainen2020joint] several studies have recently investigated the effect of biotic interactions on larger biogeographical patterns. 
Some studies show that biotic interactions can modulate the response towards environmental variations [@abrego2021accounting], as environmental harshness increases biotic interactions become less restrictive and vice versa. 
Joint species distribution models [e.g. @ovaskainen2020joint; @pichlerNewJointSpecies2021] could be used to integrate biotic interactions into freshwater typologies [@Hill2020].

## Data constrains
<!-- 4. The Effect of taxonomic resolution --> 
Due to the taxonomic resolution of the initial data sets and the varying sampling approaches, we conducted all analyses at the family level. 
Analyses at the genus or species level would have indcluded more taxa, which means more discriminating entities and thus potentially more distinct assemblages and higher cluster validity scores. 
In the analysis of @Moog2004, higher taxonomic resolution lead to more distinct ecoregions.
Similarly, @Verdonschot2006 showed that a small difference in classification strength was noticeable between 'best-available' and family-level data on a pan-European scale. 
This is plausible, as the species-level is where trait-environment interactions shape the responses to environmental conditions [e.g. @poff1997landscape], even though intraspecific variation might also be considerable [@Wong2021].
At the same time, community composition is influenced by non-environmental factors like biotic interactions, dispersal and stochasticity [@leibold2004metacommunity]. 
If responses of congeneric species are more similar to each other than to those of more distantly related species [e.g. @Marchant1995], using genus- or family-level data might reduce this "noise" [@Bowman1997]. 
Indeed, @Hawkins2000 note that across taxa groups and typologies, a higher taxonomic resolution does not always lead to greater classification strength.  
This notion is supported by many studies showing that differences between differently resolved data sets are usually small [e.g. @Furse1984; @Rutt1990; @Marchant1995; @Bowman1997; @Waite2004; @Feio2006; @Heino2007; @Heino2008; @godoy2019taxonomic] and by our mantel tests (Figure S3). 
Yet, some studies also find contrasting patterns, suggesting that higher taxonomic resolution confers significantly more information [e.g. @Heino2014].
@Marchant1995 propose that the necessary degree of taxonomic resolution scales with the spatial scale, with family-level data being sufficient for analyses that cover multiple catchments. 
This concurs with @Moog2004, and if correct would mean that reach-scale typologies, like the broad river types, are more severely handicapped by a low taxonomic resolution than regional typologies. 
Given the fact that most of the broad river types occur throughout Europe, the impact on cluster validity metrics should be small. 

The second measure we took to reduce the variation introduced by the varying sampling strategies was the transformation to presence-absence. 
Several studies have demonstrated that results can differ between presence-absence and abundance data [e.g. @Thorne_Williams_Cao_1999; @Marshall2005TaxonomicRA; @Melo2005; @Vasconcelos2013; @Heino2008].
In comparison to abundance data, binary data put less weight on highly abundant taxa and instead place equal weight on each taxon.
The focus of the analysis thus moves from changes in relative abundances to changes in composition, which likely are the more important drivers of variation at the large spatial scales we considered in this study [@Anderson_Connell_Gillanders_Diebel_Blom_Saunders_Landers_2005]. 
How large the difference between presence-absence and abundance data is, thus likely depends on the spatial scale of the study. 
All of the above studies have considered smaller spatial scales (often the catchment scale) and might thus overestimate the deviation for the spatial scale relevant for the present study. 
This is in line with the finding that different basins can be differentiated with family-level presence-absence data [@Heino2014].
In conclusion, using abundance and species-level data would likely affect our results.
To which degree can not conclusively be determined until such data exist but given the arguments above, we think the deviations would not change our conclusions. 

## Next steps for freshwater typologies

<!-- 5. future of typologies -->
We propose three likely improvements to the broad river types. 
First, intermittent rivers are common throughout Europe [@Datry_Larned_Tockner_2014;
@Stubbington_England_Wood_Sefton_2017; @Messager_Lehner_Cockburn_Lamouroux_Pella_Snelder_Tockner_Trautmann_Watt_Datry_2021] and their prevalence is projected to increase with climate change [@jaegerClimateChangePoised2014].
The effects of drying on dispersal and network connectivity make the meta-community processes discussed above especially pertinent in these systems [@Cid2020]. 
The broad river types underrepresent this distinct and widespread river type by only recognizing them in the Mediterranean. 
Second, while most classifications discussed so far are based solely on environmental attributes, biological communities can also be used as classification criteria.
Doing so could help to better represent biological interactions, dispersal and small-scale environmental variations [@DeVries2020]. 
While @DeVries2020 argue for purely biological classifications, @Hill2020 review numerous promising methods to combine biological and environmental features. 
Among them are joint species distribution models, generalized dissimilarity models [@ferrierUsingGeneralizedDissimilarity2007] and the regions of common profile [@fosterModellingBiologicalRegions2013]. 
Lastly, the combination of regional and reach-based typologies would likely result in typologies that are superior to either alone. 
As discussed above, both approaches capture important dimensions of variation: reach-scale typologies the longitudinal dimension and regional typologies the variation among large geographic areas. 
While the broad river types include region as a variable, it is only used to divide between Mediterranean and non-Mediterranean. 
Including more regions such as Illies Freshwater Ecoregions, as is proposed for System A of the WFD, the Hydroecoregions [@wassonEuropeanHydroEcoregions2007], the Biogeographic Regions or the Environmental Zones of Europe [@metzgerDescriptionsEuropeanEnvironmental2012] as is proposed by @michelleRevisionEUNISInland2021, would spatially constrain types and hence help to integrate dispersal limitations into the typology.   
However, using all types that result from a straight forward combination of the broad river types with e.g. Illies Freshwater Ecoregions clearly produces to many types too be useful. 
Therefore, ways to optimally aggregate the combined types should be derived in future work. 

## Conclusion
We evaluated three pan-European freshwater typologies as classifications of macroinvertebrate community composition.
All three performed better than would be expected of randomly assorted sites. 
However, cluster validity statistics highlighted large overlaps between clusters. 
For macroinvertebrates, the within-type similarity was too small to support the assumptions of the reference-state approach. 
A crucial next step will be to evaluate the broad river types with other biological quality elements (i.e. macrophytes, fishes and phytoplankton) as the aim of the typology must be to capture all four optimally [@Dodkins2005] and classification performance can vary strongly between taxonomic groups [@paavola2003biological].
Comparable performances with other quality elements would support the notion that other pan-European typologies should be considered. 

<!-- unassigend blurbs: 

Landuse:  
In most instances the effects of land-use on effectiveness of the typologies was minimal. This is contrary to the expectation that land-use homogenizes communities but is in line with the findings @Waite2000. In their analysis of macroinvertebrate samples from the Mid-Appalachian Highlands they found small differences between the classification strength of pristine samples compared to a random selection of samples. 

biomonitroing 

Overall this highlights the need to increase taxonomic resolution in biomonitoring.
Especially for Chironomidae and Simuliidae; two widespread Dipteran families that can be found in diverse types of rivers but are often only determined to family level. 
Chironomidae are optimal bioindicators: their larvae live in a variety of freshwater habitats [@pillot2020chironomidae], where they often dominate in terms of biomass and abundance [@armitage2012chironomidae] and the more than 20.000 species have species-specific niches [@armitage2012chironomidae; @kondo1992habitat]. 
As such they have been used to indicate pollution [@wilson1977new], general water quality [@nicacio2015chironomids] and desiccation [@punti2009environmental; @Canedo-Arguelles2016]. 
The second family, Simuliidae, is also ubiquitous and has a high species to genus ratio [~150 considering only extant taxa, @adler2016world].
The higher this ratio, the greater the loss of information when using lower level (e.g. family-level) data. 
The usefulness of Simuliidae for biomonitoring has been repeatedly demonstrated [e.g. @feld2002indication; @pramual2009agricultural].
However, as stressor effects can differ between species [@nelson2020contrasting], species-level data is necessary. 
In both families, the main obstacles to higher taxonomic resolution, are the expertise, financial resources and time necessary for precise morphological identification.   

Basing biomonitoring schemes on environmental nucleic acids [eNA, @Veilleux2021] which includes eDNA [@Taberlet2012] and eRNA [@cristescu2019can] would remove this hurdle. 
Such approaches have been advocated for repeatedly [e.g. @kelly2014harnessing; @deiner2017environmental; @pawlowski2018future] and are starting to be implemented [e.g. @pawlowski2020environmental]. 
eNA surveys are faster, less labor-intensive and minimally invasive.
Therefore, both spatial and temporal resolution of monitoring schemes could be increased cost-neutrally. 
Unlike traditional methods, they are not biased against visually hard to identify taxa (e.g. Chrionomidae or Simuliidae), cryptic or microbial taxa [@Cordier2019]. 
The biggest barrier to this promising approach, incomplete sequence databases [e.g. @kvist2013barcoding; @Cordier2019], might be surmounted with taxonomy-free approaches. 
An example is provided by @apotheloz2017taxonomy, who suggested assigning environmental quality scores to operational taxonomic units based on their occurrence at sites of known status.
--> 




