---
title             : "Fit for purpose? Evaluating the biological validity of European freshwater typology systems with invertebrate communities."
shorttitle        : "Evaluating pan-European Freshwater Typologies"

author: 
  - name          : "Jonathan F. Jupke"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Fortstraße 7, 76820 Landau, Germany"
    email         : "jonjup@protonmail.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
      - Methodology
      - Software
      - Formal analysis
  - name       : "Sebastian Birk"
    affiliation: "2,3"
    role       :
      - Writing - Review & Editing
      - Conceptualization
      - Resources
  - name       : "Mario Álvarez-Cabria"
    affiliation: "4"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Jukka Aroviita"
    affiliation: "5"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
      
  - name       : "Pepe Barquín"
    affiliation: "4"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       :  "Oscar Belmar"
    affiliation: "6"  
  - name       : "Núria Bonada"
    affiliation: "7"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Miguel Cañedo-Argüelles"
    affiliation: "8"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Gabriel Chiriac"
    affiliation: "9"
    role       :    
  - name       : "Christian K. Feld"
    affiliation: "2,3"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "M. Teresa Ferreira"
    affiliation: "10"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing    
  - name       : "Peter Haase"
    affiliation: "3,11"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Maria Lazaridou"
    affiliation: "12"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Kaisa-Leena Huttunen"
    affiliation: "13"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing

  - name       : "Marko Miliša"
    affiliation: "14"
    role       : 
      - Data curation 
      - Resources
      - Writing - Review & Editing   
  - name       : "Timo Muotka"
    affiliation: "5,13"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Riku Paavola"
    affiliation: "15"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Piotr Panek"
    affiliation: "15"
    role       : 
      - Data curation 
      - Resources
      - Writing - Review & Editing
  - name       : "Petr Pařil"
    affiliation: "17"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Edwin T. H. M. Peeters"
    affiliation: "18"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Marek Polášek"
    affiliation: "17,19"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Leonard Sandin"
    affiliation: "20"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Denes Schmera"
    affiliation: "21"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name       : "Michal Straka"
    affiliation: "17,19"
    role       : 
      - Data curation 
      - Resources
      - Writing - Review & Editing     
  - name       : "Philippe Usseglio-Polatera"
    affiliation: "22"
    role       : 
      - Data curation
      - Resources
      - Writing - Review & Editing
  - name          : "Ralf B. Schäfer"
    affiliation   : "1"
    role:         
    - Writing - Review & Editing
    - Supervision
    - Project administration
    - Conceptualization
    - Funding acquisition
  
affiliation:
  - id            : "1"
    institution   : "iES, Institute of Environmental Sciences, University of Koblenz Landau, Fortstraße 7, 76829 Landau, Germany"
  - id            : "2"
    institution   : "Centre for Water and Environmental Research, University of Duisburg-Essen, Universitätsstrasse 5, 45141 Essen, Germany" 
  - id            : "3"
    institution   : "Faculty of Biology, University of Duisburg-Essen, Universitätsstrasse 5, Essen 45141, Germany"       
  - id            : "4"
    institution   : "Environmental Hydraulics Institute, University of Cantabria, C/ Isabel Torres 15, Parque Científico y Tecnológico de Cantabria, 39011 Santander, Spain."
  - id            : "5"
    institution   : "Finnish Environment Institute, Freshwater Centre, P.O. Box 413, Paavo Havaksen tie 3, FI-90014 Oulu, Finland"
  - id            : "6"
    insitution    : "IRTA, Program of Marine and Continental Waters, Sant Carles de la Ràpita, 43540 Catalonia, Spain"
  - id            : "7"
    institution   : "Grup de Recerca “Freshwater Ecology, Hydrology and Management” (FEHM), Departament de Biologia Evolutiva, Ecologia i Ciències Ambientals, Facultat de Biologia, Institut de Recerca de la Biodiversitat (IRBio), Universitat de Barcelona (UB), Diagonal 643, 08028, Barcelona, Catalonia, Spain."
  - id            : "8"
    institution   : "Serra Húnter fellow, “Freshwater Ecology, Hydrology, and Management“ (FEHM), Departament de Biologia Evolutiva, Ecologia i Ciències Ambientals, Facultat de Biologia, Institut de Recerca de l’Aigua (IdRA), Universitat de Barcelona (UB), Diagonal 643, 08028, Barcelona, Catalonia, Spain."
  - id            : "9"
    institution   : "National Administration “Apele Romane”, Edgar Quinet 6, 010017 Bucharest, Romania"
  - id            : "10"
    institution   : "Centro de Estudos Florestais, Universidade Técnica de Lisboa, Instituto Superior de Agronomia, Tapada da Ajuda, 1349-017 Lisboa, Portugal"
  - id            : "11"
    institution   : "Department of River Ecology and Conservation, Senckenberg Research Institute and Natural History Museum Frankfurt, Clamecystrasse 12, Gelnhausen 65371, Germany"
  - id            : "12"
    institution   : "Department of Zoology, School of Biology, Aristotle University of Thessaloniki, P.O. Box 134, 54124 Thessaloníki, Greece"
  - id            : "13"
    institution   : "Department of Ecology and Genetics, University of Oulu, P.O. Box 3000, Pentti Kaiteran katu 1, FI-90014 Oulu, Finland"
 
  - id            : "14"
    institution   : "Department of Biology, Faculty of Science, University of Zagreb, Rooseveltov trg 6, 10000 Zagreb, Croatia"
  - id            : "15"
    institution   : "Oulanka Research Station, University of Oulu Infrastructure Platform, Liikasenvaarantie 134, FI-93900 Kuusamo, Finland"
  - id            : "16"
    institution   : "Departament Monitoringu Środowiska Wydział, Monitoringu i Ocen Stanu Wód, Al Jerozolimskie 92, 00-807 Warszawa, Poland"
  - id            : "17"
    institution   : "Department of Botany and Zoology, Faculty of Science, Masaryk University, Kotlářská 2, 611 37 Brno, Czech Republic"
  - id            : "18"
    institution   : "Aquatic Ecology and Water Quality Management Group, Wageningen University, P.O. Box 47, 6700 AA Wageningen, The Netherlands"
  - id            : "19"
    institution   : "T. G. Masaryk Water Research Institute, p. r. i., Mojmírovo náměstí 16, 612 00 Brno, Czech Republic"
  - id            : "20"
    institution   : "Norwegian Institute for Water Research, Gaustadalléen 21, NO-0349 Oslo, Norway"
  - id            : "21"
    institution   : "Balaton Limnological Research Institute, Klebelsberg Kuno u. 3, 8237 Tihany, Hungary"
  - id            : "22"
    institution   : "Université de Lorraine, CNRS, UMR 7360, LIEC, Laboratoire Interdisciplinaire des Environnements Continentaux, Rue du Général Delestraint, 57070 Metz, France"

abstract: |
 Humans alter the composition of freshwater communities on a global scale. International regulatory frameworks are necessary to slow down, halt and reverse the ongoing loss of freshwater biodiversity. These regulatory frameworks typically simplify freshwater ecosystems into homogeneous ecosystem types (a typology system) delineated by environmental factors. 
 Within one type, rivers that are unimpacted by human activities (i.e. in reference condition) are expected to be similar concerning physicochemical (e.g. nutrient thresholds) and biological (community composition) conditions. This assumption is crucial when assessments are based on comparisons to reference conditions, as in the Water Framework Directive (WFD). 
  The Broad River Types have recently been proposed as a pan-European typology system. 
  They unify the assortment of national typology systems and are quickly gaining traction within the research community. 
    However, it is unknown how similar biological communities are within individual Broad River Types.
 Here, we examine if the Broad River Types delineate distinct macroinvertebrate communities and whether they do it better than two older and simpler approaches based on ecoregions. To this end, we compared the similarities of communities between and within Broad River Types, the European Biogeographical Regions and Illies Freshwater Ecoregions.
    Moreover, we identified indicative and typical communities for the types of each typology and evaluated their distinctiveness and similarities. 
    All three typology systems captured more of the variation in macroinvertebrate communities than random combinations of sites. Their results were similar, but the Broad River Types always performed worse than either the Biogeographic Regions or Illies Freshwater Ecoregions. Despite reaching statistical significance, the test statistics were low in all tests indicating substantial overlap between types. We conclude that the Broad River Types do not represent a meaningful improvement upon existing freshwater typologies when used to delineate macroinvertebrate communities, and we propose possible avenues for advancement. 
  
      
keywords          : "Water Framework Directive, Ecoregions, Biomonitoring, Macroinvertebrates, River Typology"
wordcount         : 8735

bibliography      : ../parts/ref.bib
csl               : ../parts/ecology_letters.csl

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : yes
  
documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_word
---

```{r setup, include = FALSE}
library("papaja")
library("data.table")
library("officer")
r_refs("r-references.bib")
```

```{r analysis-preferences, warning=FALSE}

##  Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)

## load libraries 
pacman::p_load(grid,
               jpeg)

## load object that gives numbers of sites and samples 
## the object was created with pre-compile.R 



# out <- list()
# out$n_sites_total   <- 52900 
# out$n_samples_total <- 180188
# out$n_sites_li      <- 13228
# out$n_sites_close   <- 32219

out <- readRDS(file = "../parts/2021-10-21_site_sample_data.rds")

out.perc1 <- round(out$agg1_sites/out$non_agg_sites, 3) * 100 
out.perc2 <- round(out$agg1_samples/out$non_agg_samples, 3) * 100 
out.perc3 <- round(out$close_sites/out$non_agg_sites, 3) * 100 
out.perc4 <- round(out$close_samples/out$non_agg_samples, 3) * 100 


tab1 <- xlsx::read.xlsx("../parts/data_set_overview.xlsx", sheetIndex = 1)
tab1$new1 <- paste0(tab1$samples, "\ (", tab1$sites, ")" )
tab1$new2 <- paste0(tab1$least.impacted.samples, "\ (", tab1$lesat.impacted.sites., ")" )
tab1 <- tab1[, c(1,2,8,9,7)]
names(tab1) <- c("ID", "data set", "all samples (sites)", "least impaired samples (sites)", "sampling method")
```

# Introduction    
```{r call intro, child="../parts/introduction_sebastian_birk.rmd"}
```

# Methods 
```{r call intro, child="../parts/methods.rmd"}
```

# Results 
```{r call intro, child="../parts/results.rmd"}
```

# Discussion
```{r call intro, child="../parts/discussion.rmd"}
```

# Acknowledgements
thanks for pointing to data 
Agnez Bouchez,  Stéphanie Couprie, Lucie Clavel
Geoff Phillips, John Murray-Bligh

\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
