code <- c("ACf",    
"ACg",    
"ACh",    
"ACp",    
"ACu",    
"AL",     
"ALf",    
"ALg",    
"ALh",    
"ALj",    
"ALp",    
"ALu",    
"AN",     
"ANg",    
"ANh",    
"ANi",    
"ANm",    
"ANu",    
"AR",     
"ARa",    
"ARb",    
"ARbs",   
"ARc",    
"ARcg",   
"ARg",    
"ARh",    
"ARl",    
"ARo",    
"AT",     
"ATa",    
"ATc",    
"ATf",    
"ATu",    
"CH",     
"CHb",    
"CHe",    
"CHg",    
"CHgs",   
"CHh",    
"CHha",   
"CHhv",   
"CHi",    
"CHk",    
"CHkb",   
"CHkc",   
"CHkv",   
"CHl",    
"CHw",    
"CL",     
"CLh",    
"CLl",    
"CLp",    
"CM",     
"CMa",    
"CMc",    
"CMd",    
"CMda",   
"CMdh",   
"CMds",   
"CMe",    
"CMea",   
"CMec",   
"CMef",   
"CMep",   
"CMet",   
"CMev",   
"CMg",    
"CMh",    
"CMi",    
"CMj",    
"CMjd",   
"CMjp",   
"CMo",    
"CMu",    
"CMv",    
"CMx",    
"FL",     
"FLc",    
"FLcf",   
"FLcg",   
"FLd",    
"FLe",    
"FLef",   
"FLeg",   
"FLhi",   
"FLm",    
"FLs",    
"FLt",    
"FLu",    
"FR",     
"FRg",    
"FRh",    
"FRp",    
"FRr",    
"FRu",    
"FRx",    
"GL",     
"GLa",    
"GLd",    
"GLdh",   
"GLe",    
"GLef",   
"GLh",    
"GLi",    
"GLk",    
"GLm",    
"GLme",   
"GLmf",   
"GLt",    
"GLu",    
"GMe",    
"GR",     
"GRg",    
"GRh",    
"GY",     
"GYh",    
"GYk",    
"GYl",    
"GYp",    
"HS",     
"HSf",    
"HSfd",   
"HSi",    
"HSl",    
"HSs",    
"HSt",    
"KS",     
"KSh",    
"KSk",    
"KSkb",   
"KSl",    
"KSy",    
"LP",     
"LPc",    
"LPd",    
"LPe",    
"LPi",    
"LPk",    
"LPm",    
"LPq",    
"LPqc",   
"LPqd",   
"LPqe",   
"LPr",    
"LPu",    
"LV",     
"LVa",    
"LVaa",   
"LVal",   
"LVe",    
"LVf",    
"LVg",    
"LVh",    
"LVhp",   
"LVj",    
"LVja",   
"LVjp",   
"LVk",    
"LVo",    
"LVv",    
"LVx",    
"LVxp",   
"LVxv",   
"LX",     
"LXa",    
"LXf",    
"LXg",    
"LXh",    
"LXj",    
"LXp",    
"MGd",    
"NT",     
"NTh",    
"NTr",    
"NTu",    
"PD",     
"PDd",    
"PDe",    
"PDg",    
"PDi",    
"PDj",    
"PFg",    
"PH",     
"PHc",    
"PHg",    
"PHh",    
"PHhv",   
"PHi",    
"PHj",    
"PHjv",   
"PHl",    
"PHlv",   
"PL",     
"PLd",    
"PLe",    
"PLev",   
"PLi",    
"PLm",    
"PLu",    
"PT",     
"PTa",    
"PTd",    
"PTe",    
"PTu",    
"PZ",     
"PZb",    
"PZc",    
"PZf",    
"PZg",    
"PZh",    
"PZha",   
"PZi",    
"RG",     
"RGc",    
"RGd",    
"RGe",    
"RGep",   
"RGi",    
"RGu",    
"RGy",    
"Rge",    
"SC",     
"SCg",    
"SCh",    
"SCi",    
"SCk",    
"SCm",    
"SCn",    
"SCy",    
"SN",     
"SNg",    
"SNh",    
"SNj",    
"SNk",    
"SNm",    
"SNy",    
"VR",     
"VRd",    
"VRe",    
"VReg",   
"VRej",   
"VRen",   
"VRk",    
"VRy",    
"1 11",   
"2 22",   
"3 33",   
"4 44",   
"5 55",   
"6 66"
)
full_name <- c(
        "Ferric Acrisol",
        "Gleyic Acrisol",
        "Haplic Acrisol",
        "Plinthic Acrisol",
        "Humic Acrisol",
        "Alisol",
        "Ferric Alisol",
        "Gleyic Alisol",
        "Haplic Alisol",
        "Stagnic Alisol",
        "Plinthic Alisol",
        "Humic Alisol",
        "Andosol",
        "Gleyic Andosol",
        "Haplic Andosol",
        "Gelic Andosol",
        "Mollic Andosol",
        "Umbric Andosol",
        "Arenosol",
        "Albic Arenosol",
        "Cambic Arenosol",
        "?-Cambic Arenosol",
        "Calcaric Arenosol",
        "?-Calcaric Arenosol",
        "Gleyic Arenosol",
        "Haplic Arenosol",
        "Luvic Arenosol",
        "Ferralic Arenosol",
        "Anthrosol",
        "Aric Anthrosol",
        "Cumulic Anthrosol",
        "Fimic Anthrosol",
        "Urbic Anthrosol",
        "Chernozem",
        "Cambic Chernozem",
        "Eutric Chernozem",
        "Gleyic Chernozem",
        "?-Gleyic Chernozem",
        "Haplic Chernozem",
        "?-Haplic Chernozem",
        "?-Haplic Chernozem",
        "Gelic Chernozem",
        "Calcic Chernozem",
        "?-Calcic Chernozem",
        "?-Calcic Chernozem",
        "?-Calcic Chernozem",
        "Luvic Chernozem",
        "Glossic Chernozem",
        "Calcisol",
        "Haplic Calcisol",
        "Luvic Calcisol",
        "Petric Calcisol",
        "Cambisol",
        "Aric Cambisol",
        "Calcaric Cambisol",
        "Dystric Cambisol",
        "?-Dystric Cambisol",
        "?-Dystric Cambisol",
        "?-Dystric Cambisol",
        "Eutric Cambisol",
        "?-Eutric Cambisol",
        "?-Eutric Cambisol",
        "?-Eutric Cambisol",
        "?-Eutric Cambisol",
        "?-Eutric Cambisol",
        "?-Eutric Cambisol",
        "Gleyic Cambisol",
        "Haplic Cambisol",
        "Gelic Cambisol",
        "Stagnic Cambisol",
        "?-Stagnic Cambisol",
        "?-Stagnic Cambisol",
        "Ferralic Cambisol",
        "Humic Cambisol",
        "Vertic Cambisol",
        "Chromic Cambisol",
        "Fluvisol",
        "Calcaric Fluvisol",
        "?-Calcaric Fluvisol",
        "?-Calcaric Fluvisol",
        "Dystric Fluvisol",
        "Eutric Fluvisol",
        "?-Eutric Fluvisol",
        "?-Eutric Fluvisol",
        "?-Haplic Fluvisol",
        "Mollic Fluvisol",
        "Salic Fluvisol",
        "Thionic Fluvisol",
        "Umbric Fluvisol",
        "Ferralsol",
        "Geric Ferralsol",
        "Haplic Ferralsol",
        "Plinthic Ferralsol",
        "Rhodic Ferralsol",
        "Humic Ferralsol",
        "Xanthic Ferralsol",
        "Gleysol",
        "Andic Gleysol",
        "Dystric Gleysol",
        "?-Dystric Gleysol",
        "Eutric Gleysol",
        "?-Eutric Gleysol",
        "Haplic Gleysol",
        "Gelic Gleysol",
        "Calcic Gleysol",
        "Mollic Gleysol",
        "?-Mollic Gleysol",
        "?-Mollic Gleysol",
        "Thionic Gleysol",
        "Umbric Gleysol",
        "",
        "Greyzem",
        "Gleyic Greyzem",
        "Haplic Greyzem",
        "Gypsisol",
        "Haplic Gypsisol",
        "Calcic Gypsisol",
        "Luvic Gypsisol",
        "Petric Gypsisol",
        "Histosol",
        "Fibric Histosol",
        "?-Fibric Histosol",
        "Gelic Histosol",
        "Folic Histosol",
        "Terric Histosol",
        "Thionic Histosol",
        "Kastanozem",
        "Haplic Kastanozem",
        "Calcic Kastanozem",
        "?-Calcic Kastanozem",
        "Luvic Kastanozem",
        "Gypsic Kastanozem",
        "Leptosol",
        "Calcaric Leptosol",
        "Dystric Leptosol",
        "Eutric Leptosol",
        "Gelic Leptosol",
        "Rendzic Leptosol",
        "Mollic Leptosol",
        "Lithic Leptosol",
        "?-Lithic Leptosol",
        "?-Lithic Leptosol",
        "?-Lithic Leptosol",
        "Rhodic Leptosol",
        "Umbric Leptosol",
        "Luvisol",
        "Albic Luvisol",
        "?-Albic Luvisol",
        "?-Albic Luvisol",
        "Euric Luvisol",
        "Ferric Luvisol",
        "Gleyic Luvisol",
        "Haplic Luvisol",
        "?-Haplic Luvisol",
        "Stagnic Luvisol",
        "?-Stagnic Luvisol",
        "?-Stagnic Luvisol",
        "Calcic Luvisol",
        "Ferralic Luvisol",
        "Vertic Luvisol",
        "Chromic Luvisol",
        "?-Chromic Luvisol",
        "?-Chromic Luvisol",
        "Lixisol",
        "Albic Lixisol",
        "Ferric Lixisol",
        "Gleyic Lixisol",
        "Haplic Lixisol",
        "Stagnic Lixisol",
        "Plinthic Lixisol",
        "",
        "Nitisol",
        "Haplic Nitisol",
        "Rhodic Nitisol",
        "Humic Nitisol",
        "Podzoluvisol",
        "Dystric Podzoluvisol",
        "Eutric Podzoluvisol",
        "Gleyic Podzoluvisol",
        "Gelic Podzoluvisol",
        "Stagnic Podzoluvisol",
        "",
        "Phaeozem",
        "Calcaric Phaeozem",
        "Gleyic Phaeozem",
        "Haplic Phaeozem",
        "?-Haplic Phaeozem",
        "GelicPhaeozem",
        "Stagnic Phaeozem",
        "?-Stagnic Phaeozem",
        "Luvic Phaeozem",
        "?-Luvic Phaeozem",
        "Planosol",
        "Dystric Planosol",
        "Eutric Planosol",
        "?-Eutric Planosol",
        "Gelic Planosol",
        "Mollic Planosol",
        "Umbric Planosol",
        "Plinthosol",
        "Albic Plinthosol",
        "Dystric Plinthosol",
        "Eutric Plinthosol",
        "Humic Plinthosol",
        "Podzol",
        "Cambic Podzol",
        "Carbic Podzol",
        "Ferric Podzol",
        "Gleyic Podzol",
        "Haplic Podzol",
        "?-Haplic Podzol",
        "Gelic Podzol",
        "Regosol",
        "Calcaric Regosol",
        "Dystric Regosol",
        "Eutric Regosol",
        "?-Eutric Regosol",
        "Gelic Regosol",
        "Umbric Regosol",
        "Gypsic Regosol",
        "",
        "Solonchak",
        "Gleyic Solonchak",
        "Haplic Solonchak",
        "Gelic Solonchak",
        "Calcic Solonchak",
        "Mollic Solonchak",
        "Sodic Solonchak",
        "Gypsic Solonchak",
        "Solonetz",
        "Gleyic Solonetz",
        "Haplic Solonetz",
        "Stagnic Solonetz",
        "Calcic Solonetz",
        "Mollic Solonetz",
        "Gypsic Solonetz",
        "Vertisol",
        "Dystric Vertisol",
        "Eutric Vertisol",
        "?-Eutric Vertisol",
        "?-Eutric Vertisol",
        "?-Eutric Vertisol",
        "Calcic Vertisol",
        "Gypsic Vertisol",
        "Town",
        "Soil disturbed by man",
        "Water body",
        "Marsh",
        "Glacier",
        "Rock outcrops"
)
fao90 <- 
        data.table(code, full_name)
